"""FrootAI Solution Plays — 100 pre-tuned AI architecture blueprints.

Each play is a validated combination of Azure AI services, configuration
parameters, and architecture patterns. Plays map to FROOT layers.
"""

from dataclasses import dataclass, field
from typing import Optional

# Structured play data — each play is a tested architecture pattern
_PLAYS_DATA = [
    {"id": "01", "name": "Enterprise RAG Q&A", "description": "Production RAG pipeline with AI Search + Azure OpenAI. Hybrid retrieval, semantic ranking, citation grounding.", "complexity": "Medium", "status": "Ready", "layer": "R", "infra": ["AI Search", "Azure OpenAI", "Container Apps", "Log Analytics"], "tuning": ["temperature", "top_k", "chunk_size", "overlap"], "modules": ["R1", "R2"]},
    {"id": "02", "name": "AI Landing Zone", "description": "Foundation Azure infrastructure for AI workloads. VNet isolation, private endpoints, managed identity, RBAC, diagnostic settings.", "complexity": "Foundation", "status": "Ready", "layer": "F", "infra": ["VNet", "Private Endpoints", "RBAC", "Key Vault", "Log Analytics"], "tuning": ["network_config", "sku_tier", "gpu_quota"], "modules": ["F1", "F2"]},
    {"id": "03", "name": "Deterministic Agent", "description": "Reliable AI agent with temperature=0, JSON output schema, guardrails, and citation enforcement.", "complexity": "Medium", "status": "Ready", "layer": "O_ORCH", "infra": ["Container Apps", "Azure OpenAI", "Content Safety"], "tuning": ["temperature", "response_format", "max_tokens", "guardrail_config"], "modules": ["O1", "O2", "R3"]},
    {"id": "04", "name": "Call Center Voice AI", "description": "Voice-enabled AI customer service with real-time speech-to-text, intent routing, and voice synthesis.", "complexity": "High", "status": "Ready", "layer": "O_ORCH", "infra": ["Communication Services", "AI Speech", "Azure OpenAI"], "tuning": ["speech_config", "voice_persona", "intent_routing"], "modules": ["O1"]},
    {"id": "05", "name": "IT Ticket Resolution", "description": "Auto-classify, route, and resolve IT tickets using LLM analysis and knowledge base lookup.", "complexity": "Medium", "status": "Ready", "layer": "O_OPS", "infra": ["Azure OpenAI", "Container Apps", "Logic Apps"], "tuning": ["classification_prompts", "routing_rules", "confidence_threshold"], "modules": ["O4", "O5"]},
    {"id": "06", "name": "Document Intelligence", "description": "Extract structured data from documents using Azure Document Intelligence + GPT-4o for complex reasoning.", "complexity": "Medium", "status": "Ready", "layer": "R", "infra": ["Document Intelligence", "Azure OpenAI", "Blob Storage"], "tuning": ["extraction_prompts", "field_schemas", "confidence_threshold"], "modules": ["R1"]},
    {"id": "07", "name": "Multi-Agent Service", "description": "Supervisor agent orchestrating specialist sub-agents with handoff protocols and shared state.", "complexity": "High", "status": "Ready", "layer": "O_ORCH", "infra": ["Container Apps", "Azure OpenAI", "Cosmos DB", "Dapr"], "tuning": ["supervisor_routing", "handoff_rules", "agent_capabilities"], "modules": ["O1", "O2", "O3"]},
    {"id": "08", "name": "Copilot Studio Bot", "description": "Low-code enterprise bot built with Copilot Studio, Dataverse knowledge, and Teams integration.", "complexity": "Low", "status": "Ready", "layer": "O_ORCH", "infra": ["Copilot Studio", "Dataverse", "Teams"], "tuning": ["topic_design", "knowledge_sources", "auth_config"], "modules": ["O1"]},
    {"id": "09", "name": "AI Search Portal", "description": "Enterprise search portal with semantic ranking, hybrid retrieval, and faceted navigation.", "complexity": "Medium", "status": "Ready", "layer": "R", "infra": ["AI Search", "App Service", "Log Analytics"], "tuning": ["hybrid_weights", "scoring_profiles", "semantic_config"], "modules": ["R1", "R2"]},
    {"id": "10", "name": "Content Moderation", "description": "AI Content Safety pipeline with configurable severity thresholds and custom blocklists.", "complexity": "Low", "status": "Ready", "layer": "O_OPS", "infra": ["Content Safety", "API Management"], "tuning": ["severity_levels", "blocklists", "custom_categories"], "modules": ["O5", "O6"]},
    {"id": "11", "name": "Landing Zone Advanced", "description": "Multi-region AI infrastructure with Azure Policy, hub-spoke networking, and governance automation.", "complexity": "High", "status": "Ready", "layer": "F", "infra": ["Multi-region VNet", "Azure Policy", "Management Groups"], "tuning": ["governance_policies", "advanced_rbac", "region_config"], "modules": ["F1", "F2"]},
    {"id": "12", "name": "Model Serving AKS", "description": "GPU model inference on AKS with autoscaling, health probes, and model versioning.", "complexity": "High", "status": "Ready", "layer": "T", "infra": ["AKS", "GPU Nodes", "Container Registry"], "tuning": ["model_config", "scaling_rules", "gpu_sku"], "modules": ["T1", "T2"]},
    {"id": "13", "name": "Fine-Tuning Workflow", "description": "End-to-end model fine-tuning pipeline: dataset prep, training, evaluation, deployment.", "complexity": "High", "status": "Ready", "layer": "T", "infra": ["Azure OpenAI Fine-tuning", "Blob Storage", "ML Workspace"], "tuning": ["dataset_prep", "hyperparameters", "eval_metrics"], "modules": ["T1"]},
    {"id": "14", "name": "AI Gateway", "description": "API Management gateway for Azure OpenAI with rate limiting, token budgets, and cost tracking.", "complexity": "Medium", "status": "Ready", "layer": "O_OPS", "infra": ["API Management", "Azure OpenAI", "Log Analytics"], "tuning": ["rate_limits", "token_budgets", "routing_rules"], "modules": ["O4", "O5"]},
    {"id": "15", "name": "Multi-Modal DocProc", "description": "Vision + document processing combining Document Intelligence with GPT-4o multimodal analysis.", "complexity": "High", "status": "Ready", "layer": "R", "infra": ["Document Intelligence", "Azure OpenAI GPT-4o", "Blob Storage"], "tuning": ["extraction_config", "confidence_thresholds", "vision_prompts"], "modules": ["R1"]},
    {"id": "16", "name": "Copilot Teams Extension", "description": "Teams-embedded AI assistant with adaptive cards, SSO, and plugin architecture.", "complexity": "Medium", "status": "Ready", "layer": "O_ORCH", "infra": ["Teams", "Copilot Studio", "Bot Framework"], "tuning": ["adaptive_cards", "auth_config", "plugin_manifest"], "modules": ["O1", "O3"]},
    {"id": "17", "name": "AI Observability", "description": "Full-stack monitoring for AI workloads: custom metrics, distributed tracing, alert rules, cost dashboards.", "complexity": "Medium", "status": "Ready", "layer": "O_OPS", "infra": ["Application Insights", "Log Analytics", "Azure Monitor"], "tuning": ["custom_metrics", "alert_rules", "dashboard_config"], "modules": ["O4", "O6"]},
    {"id": "18", "name": "Prompt Management", "description": "Version-controlled prompt library with A/B testing, rollback, and environment promotion.", "complexity": "Low", "status": "Ready", "layer": "T", "infra": ["Blob Storage", "Container Apps", "Cosmos DB"], "tuning": ["prompt_templates", "ab_config", "version_strategy"], "modules": ["T2", "T3"]},
    {"id": "19", "name": "Edge AI Phi-4", "description": "On-device AI inference using quantized Phi-4 models with ONNX Runtime.", "complexity": "High", "status": "Ready", "layer": "T", "infra": ["ONNX Runtime", "Phi-4", "Windows ML"], "tuning": ["quantization", "edge_config", "model_optimization"], "modules": ["T1", "T3"]},
    {"id": "20", "name": "Anomaly Detection", "description": "Real-time anomaly detection pipeline with streaming data, statistical models, and AI-powered alerting.", "complexity": "High", "status": "Ready", "layer": "O_OPS", "infra": ["Event Hub", "Stream Analytics", "Azure OpenAI"], "tuning": ["thresholds", "detection_windows", "alert_config"], "modules": ["O4", "O5"]},
    {"id": "21", "name": "Agentic RAG", "description": "Autonomous RAG agent that iteratively retrieves, evaluates, and refines answers using multi-step reasoning.", "complexity": "High", "status": "Ready", "layer": "R", "infra": ["Azure OpenAI", "AI Search", "Container Apps", "Key Vault"], "tuning": ["retrieval_strategy", "source_ranking", "iteration_depth"], "modules": ["R1", "R2"]},
    {"id": "22", "name": "Multi-Agent Swarm", "description": "Swarm-based multi-agent system with dynamic delegation, shared memory, and convergence protocols.", "complexity": "Very High", "status": "Ready", "layer": "O_ORCH", "infra": ["Azure OpenAI", "Container Apps", "Service Bus", "Cosmos DB"], "tuning": ["team_topology", "delegation_rules", "max_turns"], "modules": ["O1", "O2"]},
    {"id": "23", "name": "Browser Automation", "description": "AI-driven browser automation agent using vision models and Playwright for web task execution.", "complexity": "High", "status": "Ready", "layer": "O_ORCH", "infra": ["Azure OpenAI Vision", "Container Apps", "Playwright"], "tuning": ["domain_allowlist", "vision_prompts", "action_timeout"], "modules": ["O1", "O2"]},
    {"id": "24", "name": "AI Code Review", "description": "Automated code review agent integrating LLM analysis with CodeQL for security and quality checks.", "complexity": "Medium", "status": "Ready", "layer": "O_OPS", "infra": ["Azure OpenAI", "GitHub Actions", "CodeQL"], "tuning": ["severity_thresholds", "review_depth", "owasp_rules"], "modules": ["O4", "O5"]},
    {"id": "25", "name": "Conversation Memory", "description": "Tiered conversation memory system with short-term, long-term, and semantic recall across sessions.", "complexity": "High", "status": "Ready", "layer": "O_ORCH", "infra": ["Azure OpenAI", "Cosmos DB", "AI Search", "Redis"], "tuning": ["memory_tier_ttls", "recall_strategy", "embedding_config"], "modules": ["O1", "O2"]},
    {"id": "26", "name": "Semantic Search Engine", "description": "Enterprise semantic search with hybrid retrieval, reranking, and personalized result boosting.", "complexity": "Medium", "status": "Ready", "layer": "R", "infra": ["AI Search", "Azure OpenAI", "Blob Storage"], "tuning": ["hybrid_weights", "reranker", "personalization"], "modules": ["R1", "R2"]},
    {"id": "27", "name": "AI Data Pipeline", "description": "Intelligent data pipeline with LLM-powered classification, PII detection, and automated enrichment.", "complexity": "High", "status": "Ready", "layer": "T", "infra": ["Azure OpenAI mini", "Data Factory", "Cosmos DB", "Event Hubs"], "tuning": ["classification_prompts", "pii_rules", "batch_size"], "modules": ["T1", "T2"]},
    {"id": "28", "name": "Knowledge Graph RAG", "description": "Graph-enhanced RAG combining knowledge graph traversal with vector search for deep reasoning.", "complexity": "High", "status": "Ready", "layer": "R", "infra": ["Azure OpenAI", "Cosmos DB Gremlin", "AI Search"], "tuning": ["graph_depth", "entity_types", "fusion_ratio"], "modules": ["R1", "R2"]},
    {"id": "29", "name": "MCP Gateway", "description": "Centralized MCP tool gateway with API management, auth policies, and usage monitoring.", "complexity": "Medium", "status": "Ready", "layer": "O_OPS", "infra": ["APIM", "Container Apps", "Monitor"], "tuning": ["rate_limits", "auth_policies", "tool_registry"], "modules": ["O3", "O4"]},
    {"id": "30", "name": "AI Security Hardening", "description": "Comprehensive AI security with content safety, red team testing, and runtime threat detection.", "complexity": "High", "status": "Ready", "layer": "O_OPS", "infra": ["Content Safety", "Azure OpenAI", "Container Apps"], "tuning": ["severity_thresholds", "blocklists", "red_team_scenarios"], "modules": ["O5", "O6"]},
    {"id": "31", "name": "Low-Code AI Builder", "description": "Visual AI pipeline builder with drag-and-drop composition and one-click deployment.", "complexity": "Medium", "status": "Ready", "layer": "O_ORCH", "infra": ["Azure OpenAI", "Container Apps", "Cosmos DB", "Static Web Apps"], "tuning": ["pipeline_templates", "deployment_targets"], "modules": ["O1", "O2"]},
    {"id": "32", "name": "AI-Powered Testing", "description": "AI test generation and mutation testing with automatic coverage analysis and regression detection.", "complexity": "Medium", "status": "Ready", "layer": "O_OPS", "infra": ["Azure OpenAI", "GitHub Actions", "Container Apps"], "tuning": ["coverage_targets", "mutation_rules", "framework_configs"], "modules": ["O4", "O5"]},
    {"id": "33", "name": "Voice AI Agent", "description": "Conversational voice agent with real-time speech processing, intent detection, and dynamic responses.", "complexity": "High", "status": "Ready", "layer": "O_ORCH", "infra": ["AI Speech", "Azure OpenAI", "Communication Services"], "tuning": ["voice_models", "intent_thresholds", "fallback_chains"], "modules": ["O1", "O2"]},
    {"id": "34", "name": "Edge AI Deployment", "description": "Edge-optimized AI inference with model quantization, cloud sync, and resource-constrained deployment.", "complexity": "High", "status": "Ready", "layer": "T", "infra": ["IoT Hub", "ONNX Runtime", "Container Instances"], "tuning": ["quantization_level", "sync_schedule", "memory_budget"], "modules": ["T1", "T3"]},
    {"id": "35", "name": "AI Compliance Engine", "description": "Automated compliance checking with policy enforcement, audit trails, and risk scoring.", "complexity": "High", "status": "Ready", "layer": "O_OPS", "infra": ["Azure OpenAI", "Azure Policy", "Key Vault", "Cosmos DB"], "tuning": ["compliance_frameworks", "audit_schedules", "risk_thresholds"], "modules": ["O5", "O6"]},
    {"id": "36", "name": "Multimodal Agent", "description": "Agent handling text, image, and audio inputs with intelligent modality routing and fusion.", "complexity": "Medium", "status": "Ready", "layer": "O_ORCH", "infra": ["Azure OpenAI Vision", "AI Vision", "Blob Storage"], "tuning": ["vision_prompts", "image_resolution", "routing"], "modules": ["O1", "O2"]},
    {"id": "37", "name": "AI-Powered DevOps", "description": "AIOps platform with intelligent incident detection, root cause analysis, and automated remediation.", "complexity": "Medium", "status": "Ready", "layer": "O_OPS", "infra": ["Azure OpenAI", "Monitor", "DevOps", "GitHub Actions"], "tuning": ["severity_rules", "runbook_config", "scaling_thresholds"], "modules": ["O4", "O5"]},
    {"id": "38", "name": "Document Understanding v2", "description": "Advanced document processing with custom extraction schemas, entity recognition, and confidence scoring.", "complexity": "High", "status": "Ready", "layer": "R", "infra": ["Document Intelligence", "Azure OpenAI", "Cosmos DB"], "tuning": ["extraction_schemas", "confidence_thresholds", "entity_types"], "modules": ["R1", "R2"]},
    {"id": "39", "name": "AI Meeting Assistant", "description": "Meeting intelligence with real-time transcription, action item extraction, and scheduling integration.", "complexity": "Medium", "status": "Ready", "layer": "O_ORCH", "infra": ["AI Speech", "Azure OpenAI", "Graph", "Container Apps"], "tuning": ["transcription_config", "action_item_rules", "scheduling"], "modules": ["O1", "O2"]},
    {"id": "40", "name": "Copilot Studio Advanced", "description": "Advanced Copilot Studio with custom agents, multi-turn orchestration, and enterprise permissions.", "complexity": "High", "status": "Ready", "layer": "O_ORCH", "infra": ["Copilot Studio", "Azure OpenAI", "Dataverse", "Graph"], "tuning": ["agent_config", "permissions", "scoping", "multi_turn_rules"], "modules": ["O1", "O2"]},
    {"id": "41", "name": "AI Red Teaming", "description": "Systematic AI red teaming with automated attack generation, vulnerability scanning, and safety evaluation.", "complexity": "High", "status": "Ready", "layer": "T", "infra": ["AI Foundry", "Content Safety", "Azure OpenAI"], "tuning": ["attack_diversity", "severity_thresholds", "jailbreak_detection"], "modules": ["T2", "T3"]},
    {"id": "42", "name": "Computer Use Agent", "description": "Vision-based computer use agent that interacts with desktop applications through screenshots and actions.", "complexity": "Very High", "status": "Ready", "layer": "O_ORCH", "infra": ["Azure OpenAI Vision", "Container Apps", "Blob Storage"], "tuning": ["vision_confidence", "action_retry", "screenshot_resolution"], "modules": ["O1", "O2"]},
    {"id": "43", "name": "AI Video Generation", "description": "AI-powered video generation and editing with content safety, quality controls, and async processing.", "complexity": "Very High", "status": "Ready", "layer": "T", "infra": ["Azure OpenAI", "Blob Storage", "Content Safety", "Service Bus"], "tuning": ["video_quality", "frame_rate", "content_safety"], "modules": ["T1", "T2"]},
    {"id": "44", "name": "Foundry Local On-Device", "description": "On-device AI with Azure AI Foundry Local for offline inference, cloud escalation, and hybrid sync.", "complexity": "High", "status": "Ready", "layer": "T", "infra": ["Azure OpenAI", "IoT Hub", "Monitor"], "tuning": ["local_model_threshold", "cloud_escalation", "sync_interval"], "modules": ["T1", "T3"]},
    {"id": "45", "name": "Real-Time Event AI", "description": "Real-time event processing with AI-powered anomaly detection, pattern matching, and instant alerting.", "complexity": "Very High", "status": "Ready", "layer": "O_OPS", "infra": ["Event Hubs", "Functions", "Azure OpenAI", "Cosmos DB", "SignalR"], "tuning": ["latency_sla", "window_size", "anomaly_threshold"], "modules": ["O4", "O5"]},
    {"id": "46", "name": "Healthcare Clinical AI", "description": "Clinical decision support with medical NLP, patient data integration, and human-in-the-loop approval.", "complexity": "Very High", "status": "Ready", "layer": "O_ORCH", "infra": ["Azure OpenAI", "Health Data Services", "AI Search", "Content Safety"], "tuning": ["clinical_confidence", "pii_redaction", "human_approval"], "modules": ["O1", "O2"]},
    {"id": "47", "name": "Synthetic Data Factory", "description": "Privacy-preserving synthetic data generation with statistical fidelity validation and bias detection.", "complexity": "High", "status": "Ready", "layer": "T", "infra": ["Azure OpenAI", "ML", "Blob Storage"], "tuning": ["privacy_epsilon", "statistical_fidelity", "bias_threshold"], "modules": ["T1", "T2"]},
    {"id": "48", "name": "AI Model Governance", "description": "End-to-end model lifecycle governance with approval gates, drift detection, and evaluation automation.", "complexity": "High", "status": "Ready", "layer": "T", "infra": ["ML", "AI Foundry", "DevOps", "Cosmos DB", "Policy"], "tuning": ["approval_gates", "drift_detection", "evaluation_frequency"], "modules": ["T2", "T3"]},
    {"id": "49", "name": "Creative AI Studio", "description": "Creative content generation platform with brand voice enforcement, safety filters, and CDN delivery.", "complexity": "High", "status": "Ready", "layer": "O_ORCH", "infra": ["Azure OpenAI", "Blob Storage", "Content Safety", "Functions", "CDN"], "tuning": ["brand_voice", "content_safety", "output_quality"], "modules": ["O1", "O2"]},
    {"id": "50", "name": "Financial Risk Intelligence", "description": "Financial risk analysis with real-time market monitoring, regulatory compliance, and fraud detection.", "complexity": "Very High", "status": "Ready", "layer": "O_OPS", "infra": ["Azure OpenAI", "AI Search", "Cosmos DB", "Event Hubs"], "tuning": ["risk_confidence", "regulatory_compliance", "fraud_sensitivity"], "modules": ["O4", "O5"]},
    {"id": "51", "name": "Autonomous Coding Agent", "description": "Self-directed coding agent with iterative code generation, test execution, and quality validation.", "complexity": "Very High", "status": "Ready", "layer": "O_ORCH", "infra": ["Azure OpenAI", "GitHub Actions", "Container Apps"], "tuning": ["code_gen_temp", "max_iterations", "test_coverage"], "modules": ["O1", "O2"]},
    {"id": "52", "name": "AI API Gateway v2", "description": "Advanced AI gateway with semantic caching, intelligent routing, and token budget management.", "complexity": "High", "status": "Ready", "layer": "O_OPS", "infra": ["APIM", "Azure OpenAI", "Redis", "Monitor"], "tuning": ["cache_similarity", "routing_score", "token_budget"], "modules": ["O4", "O5"]},
    {"id": "53", "name": "Legal Document AI", "description": "Legal document analysis with clause extraction, risk assessment, and privilege detection.", "complexity": "Very High", "status": "Ready", "layer": "R", "infra": ["Azure OpenAI", "AI Search", "Blob Storage", "Cosmos DB"], "tuning": ["clause_confidence", "risk_threshold", "privilege_sensitivity"], "modules": ["R1", "R2"]},
    {"id": "54", "name": "AI Customer Support v2", "description": "Advanced AI support with sentiment analysis, auto-resolution, and intelligent escalation routing.", "complexity": "High", "status": "Ready", "layer": "O_ORCH", "infra": ["Azure OpenAI", "AI Search", "Communication Services", "Cosmos DB"], "tuning": ["sentiment_threshold", "auto_resolution", "escalation_priority"], "modules": ["O1", "O2"]},
    {"id": "55", "name": "Supply Chain AI", "description": "AI-powered supply chain optimization with demand forecasting, risk assessment, and supplier scoring.", "complexity": "Very High", "status": "Ready", "layer": "O_OPS", "infra": ["Azure OpenAI", "Cosmos DB", "Event Hubs", "ML"], "tuning": ["forecast_horizon", "safety_stock", "supplier_risk"], "modules": ["O4", "O5"]},
    {"id": "56", "name": "Semantic Code Search", "description": "Codebase-wide semantic search with embedding-based retrieval, relevance ranking, and incremental indexing.", "complexity": "Medium", "status": "Ready", "layer": "R", "infra": ["Azure OpenAI", "AI Search", "Blob Storage"], "tuning": ["chunk_size", "relevance_threshold", "refresh_interval"], "modules": ["R1", "R2"]},
    {"id": "57", "name": "AI Translation Engine", "description": "Neural translation engine with glossary enforcement, cultural adaptation, and quality scoring.", "complexity": "High", "status": "Ready", "layer": "O_ORCH", "infra": ["Azure OpenAI", "AI Translator", "Cosmos DB", "CDN"], "tuning": ["quality_threshold", "glossary_priority", "cultural_adaptation"], "modules": ["O1", "O2"]},
    {"id": "58", "name": "Digital Twin Agent", "description": "Digital twin agent with IoT integration, predictive simulation, and anomaly-driven insights.", "complexity": "Very High", "status": "Ready", "layer": "O_OPS", "infra": ["IoT Hub", "Digital Twins", "Azure OpenAI", "Functions"], "tuning": ["anomaly_sensitivity", "prediction_horizon", "simulation_fidelity"], "modules": ["O4", "O5"]},
    {"id": "59", "name": "AI Recruiter Agent", "description": "AI recruitment assistant with candidate matching, bias detection, and skills-based scoring.", "complexity": "High", "status": "Ready", "layer": "O_ORCH", "infra": ["Azure OpenAI", "AI Search", "Cosmos DB", "Graph"], "tuning": ["match_threshold", "bias_sensitivity", "skills_weight"], "modules": ["O1", "O2"]},
    {"id": "60", "name": "Responsible AI Dashboard", "description": "Responsible AI monitoring dashboard with fairness metrics, bias tracking, and compliance reporting.", "complexity": "High", "status": "Ready", "layer": "T", "infra": ["Azure OpenAI", "ML", "Monitor", "Cosmos DB", "Static Web Apps"], "tuning": ["fairness_threshold", "bias_granularity", "report_frequency"], "modules": ["T2", "T3"]},
    {"id": "61", "name": "Content Moderation v2", "description": "Advanced content moderation with multi-category classification, severity routing, and appeal workflows.", "complexity": "High", "status": "Ready", "layer": "O_OPS", "infra": ["Content Safety", "Azure OpenAI", "Cosmos DB", "Service Bus"], "tuning": ["safety_threshold", "severity_routing", "category_weights"], "modules": ["O5", "O6"]},
    {"id": "62", "name": "Federated Learning Pipeline", "description": "Privacy-preserving federated learning with secure aggregation, differential privacy, and convergence tracking.", "complexity": "Very High", "status": "Ready", "layer": "T", "infra": ["ML", "Confidential Computing", "Blob Storage"], "tuning": ["privacy_epsilon", "aggregation_rounds", "convergence_threshold"], "modules": ["T1", "T2"]},
    {"id": "63", "name": "Fraud Detection Agent", "description": "Real-time fraud detection with streaming analysis, velocity checks, and adaptive risk scoring.", "complexity": "High", "status": "Ready", "layer": "O_OPS", "infra": ["Azure OpenAI", "Event Hubs", "Stream Analytics", "Cosmos DB"], "tuning": ["risk_score", "velocity_window", "anomaly_sensitivity"], "modules": ["O4", "O5"]},
    {"id": "64", "name": "AI Sales Assistant", "description": "AI sales copilot with lead scoring, persona-tuned outreach, and pipeline forecasting.", "complexity": "Medium", "status": "Ready", "layer": "O_ORCH", "infra": ["Azure OpenAI", "Cosmos DB", "Graph", "AI Search"], "tuning": ["lead_score", "persona_temp", "email_tone", "forecast_confidence"], "modules": ["O1", "O2"]},
    {"id": "65", "name": "AI Training Curriculum", "description": "Adaptive AI training platform with difficulty scaling, assessment automation, and personalized feedback.", "complexity": "Medium", "status": "Ready", "layer": "F", "infra": ["Azure OpenAI", "Cosmos DB", "Static Web Apps"], "tuning": ["difficulty_scaling", "assessment_threshold", "feedback_detail"], "modules": ["F1", "F2"]},
    {"id": "66", "name": "AI Infrastructure Optimizer", "description": "AI-driven infrastructure optimization with cost analysis, utilization monitoring, and scaling recommendations.", "complexity": "High", "status": "Ready", "layer": "O_OPS", "infra": ["Azure OpenAI", "Monitor", "Advisor", "Cost Management"], "tuning": ["savings_threshold", "utilization_floor", "scaling_aggressiveness"], "modules": ["O4", "O5"]},
    {"id": "67", "name": "AI Knowledge Management", "description": "Enterprise knowledge management with freshness decay, expert routing, and contextual retrieval.", "complexity": "High", "status": "Ready", "layer": "R", "infra": ["Azure OpenAI", "AI Search", "Cosmos DB", "Graph"], "tuning": ["freshness_decay", "chunk_overlap", "expert_threshold"], "modules": ["R1", "R2"]},
    {"id": "68", "name": "Predictive Maintenance AI", "description": "Predictive maintenance with IoT sensor analysis, failure probability scoring, and remaining useful life estimation.", "complexity": "High", "status": "Ready", "layer": "O_OPS", "infra": ["IoT Hub", "Azure OpenAI", "ML", "Stream Analytics", "Cosmos DB"], "tuning": ["failure_probability", "sensor_window", "rul_confidence"], "modules": ["O4", "O5"]},
    {"id": "69", "name": "Carbon Footprint Tracker", "description": "Real-time carbon accounting across cloud resources and supply chain with ESG reporting.", "complexity": "High", "status": "Ready", "layer": "O_OPS", "infra": ["Azure Monitor", "Azure OpenAI", "Cosmos DB", "Event Hubs"], "tuning": ["emission_factors", "scope_boundaries", "reporting_framework"], "modules": ["T3", "O5"]},
    {"id": "70", "name": "ESG Compliance Agent", "description": "Environmental, Social, Governance reporting with GRI, SASB, TCFD, EU CSRD regulatory compliance.", "complexity": "High", "status": "Ready", "layer": "O_OPS", "infra": ["Azure OpenAI", "Document Intelligence", "Cosmos DB", "AI Search"], "tuning": ["regulatory_frameworks", "materiality_matrix", "disclosure_rules"], "modules": ["T2", "R2"]},
    {"id": "71", "name": "Smart Energy Grid AI", "description": "AI-driven energy demand prediction, renewable optimization, and grid balancing via digital twin.", "complexity": "Very High", "status": "Ready", "layer": "O_OPS", "infra": ["IoT Hub", "Azure OpenAI", "Stream Analytics", "Digital Twins"], "tuning": ["demand_horizon", "renewable_mix", "battery_schedule"], "modules": ["T3", "O5"]},
    {"id": "72", "name": "Climate Risk Assessor", "description": "Climate scenario modeling for financial risk — physical, transition, and liability risk assessment.", "complexity": "High", "status": "Ready", "layer": "R", "infra": ["Azure OpenAI", "Azure ML", "Cosmos DB", "AI Search"], "tuning": ["climate_scenarios", "time_horizons", "risk_tolerance"], "modules": ["R2", "T2"]},
    {"id": "73", "name": "Waste & Recycling Optimizer", "description": "AI waste management — material classification, route optimization, contamination detection.", "complexity": "Medium", "status": "Ready", "layer": "O_OPS", "infra": ["AI Vision", "Azure OpenAI", "IoT Hub", "Container Apps"], "tuning": ["material_categories", "classification_confidence", "vehicle_capacity"], "modules": ["O2", "T3"]},
    {"id": "74", "name": "AI Tutoring Agent", "description": "1-on-1 personalized AI tutoring with Socratic method, knowledge gap detection, adaptive difficulty, and progress tracking.", "complexity": "Medium", "status": "Ready", "layer": "O_ORCH", "infra": ["Azure OpenAI", "Cosmos DB", "AI Search", "Static Web Apps", "Functions"], "tuning": ["socratic_depth", "difficulty_adaptation", "gap_threshold"], "modules": ["O2", "T2"]},
    {"id": "75", "name": "Exam Generation Engine", "description": "Auto-generate exams from curriculum with difficulty calibration, rubric generation, answer key creation, and anti-cheating variation.", "complexity": "Medium", "status": "Ready", "layer": "O_OPS", "infra": ["Azure OpenAI", "Blob Storage", "Cosmos DB", "Functions"], "tuning": ["difficulty_distribution", "blooms_levels", "variation_count"], "modules": ["R1", "T2"]},
    {"id": "76", "name": "Accessibility Learning Agent", "description": "Screen reader-first, dyslexia-aware learning platform with multi-modal content adaptation and personalized accessibility profiles.", "complexity": "High", "status": "Ready", "layer": "O_ORCH", "infra": ["AI Speech", "Azure OpenAI", "AI Vision", "Container Apps", "Cosmos DB"], "tuning": ["wcag_level", "dyslexia_settings", "speech_rate"], "modules": ["O2", "T2"]},
    {"id": "77", "name": "Research Paper AI", "description": "AI-powered academic research — literature review, citation network analysis, methodology critique, and research gap identification.", "complexity": "High", "status": "Ready", "layer": "R", "infra": ["Azure OpenAI", "AI Search", "Cosmos DB", "Microsoft Graph", "Functions"], "tuning": ["citation_depth", "methodology_rigor", "domain_specialization"], "modules": ["R2", "O2"]},
    {"id": "78", "name": "Precision Agriculture Agent", "description": "Satellite imagery and IoT sensor fusion for crop health monitoring, irrigation scheduling, fertilization optimization, and yield prediction using digital twin simulation.", "complexity": "Very High", "status": "Ready", "layer": "O_ORCH", "infra": ["Azure IoT Hub", "Azure AI Vision", "Azure OpenAI", "Azure Digital Twins", "Azure Machine Learning"], "tuning": ["sensor_sampling_rate", "imagery_frequency", "irrigation_thresholds"], "modules": ["T3", "O5"]},
    {"id": "79", "name": "Food Safety Inspector AI", "description": "HACCP compliance automation with contamination detection — farm to fork traceability, temperature monitoring, pathogen risk scoring, and audit trail generation.", "complexity": "High", "status": "Ready", "layer": "O_OPS", "infra": ["Azure Document Intelligence", "Azure OpenAI", "Azure Cosmos DB", "Azure Event Hubs", "Azure IoT Hub"], "tuning": ["temperature_thresholds", "pathogen_risk_models", "audit_retention"], "modules": ["R2", "T2"]},
    {"id": "80", "name": "Biodiversity Monitor", "description": "AI-powered species identification from camera trap, drone, and acoustic sensor data with ecosystem health scoring and conservation priority alerts.", "complexity": "High", "status": "Ready", "layer": "O_ORCH", "infra": ["Azure AI Vision", "Azure OpenAI", "Azure IoT Hub", "Azure Cosmos DB", "Azure Functions"], "tuning": ["species_confidence", "camera_schedule", "acoustic_frequency"], "modules": ["F1", "O2"]},
    {"id": "81", "name": "Property Valuation AI", "description": "Automated property appraisal combining comparable sales analysis, market trend prediction, neighborhood scoring, and satellite imagery assessment for real estate valuation and mortgage underwriting.", "complexity": "High", "status": "Ready", "layer": "R", "infra": ["Azure OpenAI", "Azure AI Search", "Azure Cosmos DB", "Azure Machine Learning", "Azure Functions"], "tuning": ["comparable_radius", "market_trend_window", "neighborhood_score_weights"], "modules": ["R2", "T3"]},
    {"id": "82", "name": "Construction Safety AI", "description": "Real-time construction site monitoring using computer vision for PPE compliance detection, hazard identification, unauthorized zone entry alerts, and safety incident reporting with photo evidence.", "complexity": "High", "status": "Ready", "layer": "O_ORCH", "infra": ["Azure AI Vision", "Azure IoT Hub", "Azure OpenAI", "Azure Container Apps", "Azure Cosmos DB"], "tuning": ["ppe_detection_confidence", "hazard_zone_definitions", "alert_escalation_rules"], "modules": ["O2", "T3"]},
    {"id": "83", "name": "Building Energy Optimizer", "description": "HVAC, lighting, and occupancy optimization via digital twin simulation of commercial buildings. Reduces energy consumption 20-40% through AI-driven scheduling, predictive maintenance, and renewable integration.", "complexity": "Very High", "status": "Ready", "layer": "O_ORCH", "infra": ["Azure Digital Twins", "Azure IoT Hub", "Azure OpenAI", "Azure Functions", "Azure Cosmos DB"], "tuning": ["hvac_scheduling_rules", "occupancy_prediction_model", "lighting_automation_profiles"], "modules": ["T3", "O5"]},
    {"id": "84", "name": "Citizen Services Chatbot", "description": "Multi-language municipal services AI assistant with form filling guidance, appointment scheduling, permit status tracking, FAQ resolution, and human agent escalation for complex cases.", "complexity": "Medium", "status": "Ready", "layer": "R", "infra": ["Azure OpenAI", "Azure AI Translator", "Azure Communication Services", "Azure AI Search", "Azure Cosmos DB"], "tuning": ["supported_languages", "escalation_confidence_threshold", "service_catalog_scope"], "modules": ["R2", "O2", "T2"]},
    {"id": "85", "name": "Policy Impact Analyzer", "description": "Regulatory change detection with cross-sector impact assessment, stakeholder mapping, public comment analysis, and automated briefing generation for legislative and executive decision-makers.", "complexity": "High", "status": "Ready", "layer": "T", "infra": ["Azure OpenAI", "Azure AI Search", "Azure Document Intelligence", "Azure Cosmos DB", "Azure Functions"], "tuning": ["regulatory_source_feeds", "impact_assessment_depth", "stakeholder_categories"], "modules": ["R2", "T2", "T3"]},
    {"id": "86", "name": "Public Safety Analytics", "description": "Crime pattern prediction with resource allocation optimization, community sentiment analysis from social media and 311 calls, and real-time incident dashboard for law enforcement and emergency management.", "complexity": "Very High", "status": "Ready", "layer": "T", "infra": ["Azure OpenAI", "Azure Machine Learning", "Azure Event Hubs", "Azure Cosmos DB", "Azure Stream Analytics"], "tuning": ["prediction_time_window", "resource_allocation_zones", "sentiment_source_feeds"], "modules": ["T3", "T2", "O2"]},
    {"id": "87", "name": "Dynamic Pricing Engine", "description": "Real-time price optimization engine analyzing demand signals, competitor pricing, inventory levels, seasonality, and customer segments to maximize revenue while maintaining price fairness and brand perception.", "complexity": "High", "status": "Ready", "layer": "T", "infra": ["Azure OpenAI", "Azure Event Hubs", "Azure Cosmos DB", "Azure Redis Cache", "Azure Machine Learning"], "tuning": ["price_elasticity_model", "competitor_monitoring_frequency", "inventory_weight_factor"], "modules": ["T3", "O2", "F1"]},
    {"id": "88", "name": "Visual Product Search", "description": "Image-based product discovery combining reverse image search, visual similarity matching, style recommendations, and virtual try-on capabilities for fashion, furniture, and home decor retailers.", "complexity": "High", "status": "Ready", "layer": "R", "infra": ["Azure AI Vision", "Azure OpenAI", "Azure AI Search", "Azure Container Apps", "Azure Cosmos DB"], "tuning": ["visual_similarity_threshold", "style_recommendation_depth", "product_catalog_refresh_rate"], "modules": ["R2", "F1", "O2"]},
    {"id": "89", "name": "Retail Inventory Predictor", "description": "Demand forecasting and inventory optimization combining historical sales data, weather patterns, social media trends, and economic indicators to predict stock needs and automate supplier reordering.", "complexity": "High", "status": "Ready", "layer": "T", "infra": ["Azure OpenAI", "Azure Machine Learning", "Azure Cosmos DB", "Azure Event Hubs", "Azure Functions"], "tuning": ["forecast_horizon_days", "safety_stock_multiplier", "reorder_point_formula"], "modules": ["T3", "O5", "F1"]},
    {"id": "90", "name": "Network Optimization Agent", "description": "5G/LTE network capacity planning with AI-driven anomaly detection, self-healing automation, traffic prediction, and cell tower load balancing using digital twin simulation of network topology.", "complexity": "Very High", "status": "Ready", "layer": "T", "infra": ["Azure IoT Hub", "Azure Stream Analytics", "Azure OpenAI", "Azure Digital Twins", "Azure Cosmos DB"], "tuning": ["traffic_prediction_horizon", "anomaly_detection_sensitivity", "self_healing_trigger_rules"], "modules": ["T3", "O5", "O2"]},
    {"id": "91", "name": "Customer Churn Predictor", "description": "Multi-signal churn scoring combining usage patterns, billing history, support interactions, network quality metrics, and competitive offers to predict churn risk and generate personalized retention campaigns.", "complexity": "High", "status": "Ready", "layer": "T", "infra": ["Azure OpenAI", "Azure Machine Learning", "Azure Cosmos DB", "Azure Communication Services", "Azure Functions"], "tuning": ["churn_risk_threshold", "retention_offer_budget", "signal_decay_weights"], "modules": ["T3", "O2", "F1"]},
    {"id": "92", "name": "Telecom Fraud Shield", "description": "Real-time telecom fraud detection covering SIM swap attacks, international revenue share fraud, subscription fraud, Wangiri callbacks, and toll fraud with sub-second blocking and explainable alert generation.", "complexity": "High", "status": "Ready", "layer": "T", "infra": ["Azure Event Hubs", "Azure Stream Analytics", "Azure OpenAI", "Azure Cosmos DB", "Azure Functions"], "tuning": ["sim_swap_detection_window", "fraud_score_threshold", "velocity_check_limits"], "modules": ["T3", "R3", "O2"]},
    {"id": "93", "name": "Continual Learning Agent", "description": "Agent that persists knowledge across sessions, reflects on failures, detects patterns in tool outcomes, and surfaces accumulated learnings so each session starts smarter. Implements memory hooks, reflection patterns, and knowledge distillation for ever-improving AI assistance.", "complexity": "Very High", "status": "Ready", "layer": "T", "infra": ["Azure OpenAI", "Azure Cosmos DB", "Azure AI Search", "Azure Redis Cache", "Azure Functions"], "tuning": ["memory_retention_policy", "reflection_trigger_rules", "knowledge_distillation_frequency"], "modules": ["O2", "T3", "R2"]},
    {"id": "94", "name": "AI Podcast Generator", "description": "Text-to-podcast pipeline with multi-speaker voice synthesis, music transitions, chapter markers, and content safety review. Converts blog posts, research papers, or meeting notes into professionally narrated audio content using Azure AI Voice Live SDK.", "complexity": "High", "status": "Ready", "layer": "T", "infra": ["Azure AI Speech", "Azure OpenAI", "Azure Blob Storage", "Azure CDN", "Azure Functions"], "tuning": ["voice_persona_selection", "speaking_rate", "music_transition_style"], "modules": ["F1", "T3", "T2"]},
    {"id": "95", "name": "Multimodal Search Engine v2", "description": "Unified search across images, text, code, and audio with cross-modal reasoning. A user can search by uploading an image and get related code snippets, documentation, and audio explanations. Combines Azure AI Search vector indexes across modalities with GPT-4o for cross-modal synthesis.", "complexity": "Very High", "status": "Ready", "layer": "R", "infra": ["Azure AI Search", "Azure AI Vision", "Azure AI Speech", "Azure OpenAI", "Azure Container Apps"], "tuning": ["cross_modal_fusion_weights", "modality_specific_index_config", "result_diversity_score"], "modules": ["R2", "F1", "T3"]},
    {"id": "96", "name": "Real-Time Voice Agent v2", "description": "Next-generation bidirectional WebSocket voice agent using Azure AI Voice Live SDK with MCP tool integration, voice activity detection, function calling during conversation, avatar rendering, and real-time transcription. Sub-200ms response latency for natural conversational AI.", "complexity": "Very High", "status": "Ready", "layer": "O", "infra": ["Azure AI Voice Live", "Azure OpenAI", "Azure Container Apps", "Azure Functions", "Azure Cosmos DB"], "tuning": ["voice_activity_detection_mode", "response_latency_target", "function_calling_timeout"], "modules": ["O2", "O3", "T3"]},
    {"id": "97", "name": "AI Data Marketplace", "description": "Platform for publishing, discovering, and monetizing synthetic and anonymized datasets. Differential privacy validation, statistical fidelity scoring, usage-based billing, and API-first data access for AI training and testing workflows.", "complexity": "High", "status": "Ready", "layer": "T", "infra": ["Azure Machine Learning", "Azure Blob Storage", "Azure API Management", "Azure Cosmos DB", "Azure Functions"], "tuning": ["privacy_epsilon_budget", "pricing_model_config", "data_quality_thresholds"], "modules": ["T3", "T2", "O4"]},
    {"id": "98", "name": "Agent Evaluation Platform", "description": "Automated evaluation suite for any AI agent — standardized benchmarks, regression testing, A/B experimentation, human preference scoring, and leaderboard ranking. Evaluates agents across quality, safety, speed, cost, and user satisfaction dimensions.", "complexity": "High", "status": "Ready", "layer": "T", "infra": ["Azure OpenAI", "Azure Container Apps", "Azure Cosmos DB", "Azure Machine Learning", "Azure Functions"], "tuning": ["benchmark_suite_selection", "regression_threshold", "ab_traffic_split"], "modules": ["T3", "T2", "O2"]},
    {"id": "99", "name": "Enterprise AI Governance Hub", "description": "Central control plane for all AI models, agents, and APIs across an enterprise. Model registry with approval gates, policy enforcement via Azure Policy, cost attribution dashboards, safety monitoring, and regulatory compliance tracking for SOX, EU AI Act, and ISO 42001.", "complexity": "Very High", "status": "Ready", "layer": "T", "infra": ["Azure API Management", "Azure Policy", "Azure Monitor", "Azure Cosmos DB", "Azure Machine Learning", "Azure Key Vault"], "tuning": ["approval_gate_thresholds", "policy_enforcement_rules", "cost_attribution_model"], "modules": ["T3", "T2", "O4", "O5"]},
    {"id": "100", "name": "FAI Meta-Agent", "description": "The crown jewel — a self-orchestrating super-agent that understands user goals, selects and chains the appropriate FAI solution plays, provisions infrastructure, configures primitives, runs evaluation, and delivers production-ready AI systems. It is the FAI Protocol made autonomous — the agent that builds agents.", "complexity": "Very High", "status": "Ready", "layer": "O", "infra": ["Azure OpenAI", "Azure MCP Server", "Azure Container Apps", "Azure Cosmos DB", "Azure AI Search", "Azure Key Vault"], "tuning": ["play_selection_strategy", "chain_depth_limit", "budget_per_orchestration"], "modules": ["O2", "O3", "T3", "O4", "R2"]},
    {"id": "101", "name": "Pester Test Development", "description": "AI-assisted PowerShell test generation using Pester 5.x framework. 7-phase pipeline: AST-based discovery, testability assessment, dependency mapping, legacy code refactoring (Add-Type thin wrappers), comprehensive test generation with mocking, and coverage enforcement (>90% JaCoCo). Supports greenfield TDD, brownfield legacy code, Azure Policy testing, and CI/CD integration (Azure DevOps + GitHub Actions).", "complexity": "Medium", "status": "Ready", "layer": "T", "infra": ["Azure DevOps", "Azure Storage"], "tuning": ["coverage_target", "mock_verification_mode", "test_parallelism"], "modules": ["T3", "O3", "O4"]},
]


@dataclass
class SolutionPlay:
    """A FrootAI solution play — a validated Azure AI architecture pattern."""
    id: str
    name: str
    description: str
    complexity: str
    status: str
    layer: str
    infra: list[str] = field(default_factory=list)
    tuning: list[str] = field(default_factory=list)
    modules: list[str] = field(default_factory=list)

    @staticmethod
    def all() -> list["SolutionPlay"]:
        """Get all 101 solution plays."""
        return [SolutionPlay(**p) for p in _PLAYS_DATA]

    @staticmethod
    def get(play_id: str) -> Optional["SolutionPlay"]:
        """Get a play by ID (e.g. '01') or name substring (e.g. 'rag')."""
        for p in _PLAYS_DATA:
            if p["id"] == play_id or play_id.lower() in p["name"].lower():
                return SolutionPlay(**p)
        return None

    @staticmethod
    def by_layer(layer: str) -> list["SolutionPlay"]:
        """Get all plays in a FROOT layer (F, R, O_ORCH, O_OPS, T)."""
        return [SolutionPlay(**p) for p in _PLAYS_DATA if p["layer"] == layer]

    @staticmethod
    def by_status(status: str) -> list["SolutionPlay"]:
        """Get plays by status ('Ready' or 'Skeleton')."""
        return [SolutionPlay(**p) for p in _PLAYS_DATA if p["status"] == status]

    @staticmethod
    def ready() -> list["SolutionPlay"]:
        """Get all production-ready plays."""
        return SolutionPlay.by_status("Ready")

    @staticmethod
    def search(query: str) -> list["SolutionPlay"]:
        """Search plays by keyword in name, description, or infra."""
        q = query.lower()
        return [SolutionPlay(**p) for p in _PLAYS_DATA
                if q in p["name"].lower() or q in p["description"].lower() or q in " ".join(p["infra"]).lower()]

    def __repr__(self) -> str:
        return f"SolutionPlay(id='{self.id}', name='{self.name}', complexity='{self.complexity}')"

    def __str__(self) -> str:
        return f"[{self.id}] {self.name} ({self.complexity})"

    def to_dict(self) -> dict:
        """Serialize to dictionary."""
        return {"id": self.id, "name": self.name, "description": self.description,
                "complexity": self.complexity, "status": self.status, "layer": self.layer,
                "infra": self.infra, "tuning": self.tuning, "modules": self.modules}

    def to_json(self) -> str:
        """Serialize to JSON string."""
        import json
        return json.dumps(self.to_dict(), indent=2)
