import * as assert from "node:assert/strict";
import { analyzeRepository } from "../repository-intelligence/analyzer";
import { shouldRead } from "../repository-intelligence/scanPolicy";
import { SOLUTION_PLAYS } from "../data/plays";

const report = analyzeRepository({ name: "rag-app", files: ["README.md", "package.json", "src/vector-search.ts", "evaluation/groundedness.json", "infra/main.bicep"], text: { "README.md": "Production RAG with semantic search, embeddings, MCP agents, and grounded answers.", "package.json": "@azure/search-documents @modelcontextprotocol/sdk" } }, SOLUTION_PLAYS, () => "2026-08-28T00:00:00Z");
assert.equal(report.source, "local-read-only");
assert.equal(report.recommendationMode, "evidence-ranked");
assert.ok(report.signals.some(({ id }) => id === "rag"));
assert.ok(report.signals.some(({ id }) => id === "agent"));
assert.equal(report.recommendations[0]?.play.cat, "rag");
assert.ok(report.recommendations[0]?.reasons.length);
assert.ok(report.technologies.some(({ name }) => name === "TypeScript / JavaScript"));
assert.ok(report.technologies.some(({ name }) => name === "Infrastructure"));
assert.equal(report.inspectedMetadataCount, 2);
assert.equal(report.readiness.find(({ id }) => id === "definition")?.status, "detected");
assert.equal(report.readiness.find(({ id }) => id === "evaluation")?.status, "detected");
assert.equal(shouldRead("package.json"), true);
assert.equal(shouldRead("infra/main.bicep"), true);
assert.equal(shouldRead(".env"), false);
assert.equal(shouldRead("config/.npmrc"), false);
const sparse = analyzeRepository({ name: "new-workspace", files: ["README.md"], text: { "README.md": "New project" } }, SOLUTION_PLAYS, () => "2026-08-29T00:00:00Z");
assert.equal(sparse.signals[0]?.id, "baseline");
assert.equal(sparse.recommendationMode, "generic-starters");
assert.deepEqual(sparse.recommendations.slice(0, 3).map(({ play }) => play.id), ["01", "02", "17"]);
assert.ok(sparse.recommendations.every(({ reasons }) => reasons.length));
assert.equal(sparse.readiness.find(({ id }) => id === "infrastructure")?.status, "gap");
assert.equal(sparse.readiness.find(({ id }) => id === "security")?.status, "gap");
const proseOnly = analyzeRepository({ name: "planning-notes", files: ["README.md"], text: { "README.md": "We may add RAG, evaluation, guardrails, and infrastructure later." } }, SOLUTION_PLAYS);
assert.equal(proseOnly.recommendationMode, "generic-starters");
assert.equal(proseOnly.signals[0]?.id, "baseline");
assert.equal(proseOnly.readiness.find(({ id }) => id === "evaluation")?.status, "gap");
assert.equal(proseOnly.readiness.find(({ id }) => id === "security")?.status, "gap");
console.log("Repository Intelligence tests passed");
