/**
 * v6.8 commands — surface the new MCP tools (analyze_workspace,
 * scaffold_component, get_play_config, get_dependencies, generate_bicep,
 * run_eval_live) in the VS Code command palette.
 *
 * Each command:
 *   - prompts for the parameters the user can't infer
 *   - shells out to `npx frootai-mcp@latest` once with --tool / --args
 *   - renders the markdown result in a webview panel
 *
 * Why shelling out instead of using a long-lived MCP client?
 *   - Avoids holding a duplicate MCP session alongside the user's chat agent
 *   - Each command is short-lived; spawn cost is acceptable for UI commands
 *   - Falls back to a friendly error if the global MCP server is unreachable
 */
import * as vscode from 'vscode';
import { spawn } from 'child_process';

// ─────────────────────────────────────────────────────────────────────────────
// Helpers
// ─────────────────────────────────────────────────────────────────────────────

interface RunMcpResult {
    ok: boolean;
    text: string;
    durationMs: number;
}

/** Spawn `npx frootai-mcp@latest --once --tool <name> --args <json>`. */
async function runMcpTool(toolName: string, args: Record<string, unknown>): Promise<RunMcpResult> {
    const start = Date.now();
    return new Promise((resolveResult) => {
        const child = spawn('npx', ['-y', 'frootai-mcp@latest', '--once', '--tool', toolName, '--args', JSON.stringify(args)], {
            shell: true,
            stdio: ['ignore', 'pipe', 'pipe'],
            env: process.env,
        });
        let stdout = '';
        let stderr = '';
        child.stdout?.on('data', (d) => (stdout += d.toString('utf-8')));
        child.stderr?.on('data', (d) => (stderr += d.toString('utf-8')));
        child.on('close', (code) => {
            const durationMs = Date.now() - start;
            if (code === 0) {
                resolveResult({ ok: true, text: stdout, durationMs });
            } else {
                resolveResult({ ok: false, text: stderr || stdout || `Exit code ${code}`, durationMs });
            }
        });
        child.on('error', (e) => resolveResult({ ok: false, text: e.message, durationMs: Date.now() - start }));
    });
}

/** Open a webview panel with a markdown-style preformatted body. */
function openMarkdownPanel(title: string, body: string, sourceCommand: string): void {
    const panel = vscode.window.createWebviewPanel(
        `frootai.${sourceCommand}`,
        title,
        vscode.ViewColumn.Beside,
        { enableScripts: false, retainContextWhenHidden: true },
    );
    const escaped = body
        .replace(/&/g, '&amp;')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;');
    panel.webview.html = `<!doctype html>
<html>
  <head>
    <meta charset="utf-8" />
    <style>
      body { font-family: var(--vscode-font-family); padding: 16px; line-height: 1.5; color: var(--vscode-foreground); }
      pre { background: var(--vscode-textCodeBlock-background, #2d2d30); padding: 12px; border-radius: 6px; overflow-x: auto; white-space: pre-wrap; }
      h1 { margin-top: 0; font-size: 1.4em; }
      .footer { margin-top: 24px; font-size: 0.85em; color: var(--vscode-descriptionForeground); }
    </style>
  </head>
  <body>
    <h1>${title}</h1>
    <pre>${escaped}</pre>
    <div class="footer">Generated by ${sourceCommand} via frootai-mcp@latest</div>
  </body>
</html>`;
}

function getWorkspaceRoot(): string | undefined {
    return vscode.workspace.workspaceFolders?.[0]?.uri.fsPath;
}

async function withProgress<T>(title: string, fn: () => Promise<T>): Promise<T> {
    return vscode.window.withProgress(
        { location: vscode.ProgressLocation.Notification, title, cancellable: false },
        async () => fn(),
    );
}

// ─────────────────────────────────────────────────────────────────────────────
// Component / play / language pickers
// ─────────────────────────────────────────────────────────────────────────────

const COMPONENT_IDS = [
    'managed-identity-init', 'application-insights-init', 'azure-keyvault-secret',
    'azure-openai-streaming', 'azure-openai-structured-output', 'azure-search-hybrid',
    'azure-speech-stt', 'azure-speech-tts', 'fastapi-websocket-audio',
    'communication-services-call-automation', 'document-intelligence-ocr',
    'content-safety-check', 'azure-cosmos-client', 'event-hub-consumer',
    'prompt-shields-defense', 'event-grid-publisher', 'signalr-realtime',
    'azure-monitor-query', 'service-bus-sender', 'azure-aks-deployment',
];

const PLAY_IDS = ['01', '03', '04', '06', '07', '09', '13', '14', '17', '21', '22', '33'];

async function pickComponent(): Promise<string | undefined> {
    return vscode.window.showQuickPick(COMPONENT_IDS, {
        title: 'Pick a component to scaffold',
        matchOnDescription: true,
    });
}

async function pickPlay(): Promise<string | undefined> {
    return vscode.window.showQuickPick(PLAY_IDS, { title: 'Pick a solution play' });
}

async function pickLanguage(): Promise<'python' | 'typescript' | 'csharp' | undefined> {
    const v = await vscode.window.showQuickPick(['python', 'typescript', 'csharp'], { title: 'Pick a target language' });
    return v as 'python' | 'typescript' | 'csharp' | undefined;
}

// ─────────────────────────────────────────────────────────────────────────────
// Commands
// ─────────────────────────────────────────────────────────────────────────────

export async function analyzeWorkspaceCmd(): Promise<void> {
    const cwd = getWorkspaceRoot();
    if (!cwd) {
        vscode.window.showErrorMessage('FrootAI: no workspace folder open.');
        return;
    }
    const r = await withProgress('FrootAI: analyzing workspace…', () =>
        runMcpTool('analyze_workspace', { cwd, depth: 'shallow', format: 'markdown' }),
    );
    if (!r.ok) {
        vscode.window.showErrorMessage(`FrootAI: analyze_workspace failed — ${r.text.slice(0, 200)}`);
        return;
    }
    openMarkdownPanel(`FrootAI — Workspace Analysis (${r.durationMs}ms)`, r.text, 'analyzeWorkspace');
}

export async function scaffoldComponentCmd(): Promise<void> {
    const id = await pickComponent();
    if (!id) return;
    const lang = await pickLanguage();
    if (!lang) return;
    const cwd = getWorkspaceRoot();
    const r = await withProgress(`FrootAI: scaffolding ${id} (${lang})…`, () =>
        runMcpTool('scaffold_component', {
            component: id,
            language: lang,
            workspaceRoot: cwd,
            format: 'markdown',
        }),
    );
    if (!r.ok) {
        vscode.window.showErrorMessage(`FrootAI: scaffold_component failed — ${r.text.slice(0, 200)}`);
        return;
    }
    openMarkdownPanel(`FrootAI — ${id} (${lang})`, r.text, 'scaffoldComponent');
}

export async function getPlayConfigCmd(): Promise<void> {
    const play = await pickPlay();
    if (!play) return;
    const r = await withProgress(`FrootAI: loading config for play ${play}…`, () =>
        runMcpTool('get_play_config', { play, format: 'markdown' }),
    );
    if (!r.ok) {
        vscode.window.showErrorMessage(`FrootAI: get_play_config failed — ${r.text.slice(0, 200)}`);
        return;
    }
    openMarkdownPanel(`FrootAI — Play ${play} Configs`, r.text, 'getPlayConfig');
}

export async function getDependenciesCmd(): Promise<void> {
    const play = await pickPlay();
    if (!play) return;
    const lang = await vscode.window.showQuickPick(['all', 'python', 'typescript', 'csharp'], {
        title: 'Language for dependencies',
    });
    if (!lang) return;
    const r = await withProgress(`FrootAI: loading deps for play ${play} (${lang})…`, () =>
        runMcpTool('get_dependencies', { play, language: lang, format: 'markdown' }),
    );
    if (!r.ok) {
        vscode.window.showErrorMessage(`FrootAI: get_dependencies failed — ${r.text.slice(0, 200)}`);
        return;
    }
    openMarkdownPanel(`FrootAI — Play ${play} Dependencies (${lang})`, r.text, 'getDependencies');
}

export async function generateBicepCmd(): Promise<void> {
    const play = await pickPlay();
    if (!play) return;
    const env = await vscode.window.showQuickPick(['dev', 'staging', 'prod'], {
        title: 'Target environment',
    });
    if (!env) return;
    const region = await vscode.window.showInputBox({
        title: 'Azure region',
        value: 'eastus2',
    });
    if (!region) return;
    const r = await withProgress(`FrootAI: generating Bicep for play ${play} (${env}/${region})…`, () =>
        runMcpTool('generate_bicep', { play, environment: env, region, format: 'markdown' }),
    );
    if (!r.ok) {
        vscode.window.showErrorMessage(`FrootAI: generate_bicep failed — ${r.text.slice(0, 200)}`);
        return;
    }
    openMarkdownPanel(`FrootAI — Play ${play} Bicep IaC (${env})`, r.text, 'generateBicep');
}

export async function runEvalLiveCmd(): Promise<void> {
    const endpoint = await vscode.window.showInputBox({
        title: 'Endpoint URL to evaluate',
        placeHolder: 'http://localhost:8000/ask',
    });
    if (!endpoint) return;
    const cwd = getWorkspaceRoot();
    const testSetPath = await vscode.window.showInputBox({
        title: 'Path to JSONL test set (relative to workspace, optional)',
        value: 'evaluation/test-set.jsonl',
    });
    const evaluator = await vscode.window.showQuickPick(['simple', 'llm', 'azure-ai-evaluation'], {
        title: 'Evaluator backend',
    });
    if (!evaluator) return;
    const r = await withProgress(`FrootAI: running live evaluation against ${endpoint}…`, () =>
        runMcpTool('run_eval_live', {
            endpoint,
            testSetPath,
            workspaceRoot: cwd,
            evaluator,
            format: 'markdown',
        }),
    );
    if (!r.ok) {
        vscode.window.showErrorMessage(`FrootAI: run_eval_live failed — ${r.text.slice(0, 200)}`);
        return;
    }
    openMarkdownPanel(`FrootAI — Live Evaluation`, r.text, 'runEvalLive');
}

// ─────────────────────────────────────────────────────────────────────────────
// Public registrar
// ─────────────────────────────────────────────────────────────────────────────

export const V68_COMMANDS: Array<{ id: string; title: string; handler: () => Promise<void> }> = [
    { id: 'frootai.analyzeWorkspace', title: 'FrootAI: Analyze Workspace (v6.8+)', handler: analyzeWorkspaceCmd },
    { id: 'frootai.scaffoldComponent', title: 'FrootAI: Scaffold Component (v6.8+)', handler: scaffoldComponentCmd },
    { id: 'frootai.getPlayConfig', title: 'FrootAI: Get Play Config (v6.8+)', handler: getPlayConfigCmd },
    { id: 'frootai.getDependencies', title: 'FrootAI: Get Dependencies (v6.8+)', handler: getDependenciesCmd },
    { id: 'frootai.generateBicep', title: 'FrootAI: Generate Bicep IaC (v6.8+)', handler: generateBicepCmd },
    { id: 'frootai.runEvalLive', title: 'FrootAI: Run Live Evaluation (v6.8+)', handler: runEvalLiveCmd },
];
