import { Search, Mountain, Target, Phone, Ticket, FileText, Bot, MessageCircle, Shield, Settings, Microscope, DoorOpen, Image, Users, BarChart3, FileEdit, Smartphone, AlertTriangle, type LucideIcon } from "lucide-react";

export interface PlayData {
  id: string;
  slug: string;
  name: string;
  Icon: LucideIcon;
  complexity: string;
  status: string;
  tagline: string;
  description: string;
  services: string[];
  pattern: string;
  devkit: string[];
  tunekit: string[];
  tuningParams: string[];
  costDev: string;
  costProd: string;
  color: string;
  github: string;
}

export const plays: PlayData[] = [
  {
    id: "01", slug: "01-enterprise-rag", name: "Enterprise RAG Q&A",
    Icon: Search, complexity: "Medium", status: "Ready",
    tagline: "Production RAG with hybrid search, semantic reranking, and pre-tuned guardrails.",
    description: "Build a production-grade Retrieval-Augmented Generation system. AI Search indexes your documents, GPT-4o generates grounded answers with citations, and Container Apps hosts the API. Pre-tuned with temp=0.1, hybrid 60/40 search, top-k=5, and semantic reranker for optimal quality.",
    services: ["AI Search", "Azure OpenAI (gpt-4o)", "Container Apps", "Blob Storage"],
    pattern: "RAG: hybrid search, chunking, semantic reranking",
    devkit: ["agent.md — citation rules, abstention, few-shot examples", "instructions.md — system prompt + guardrails", "copilot-instructions.md — project context", "mcp/index.js — search, indexer, evaluator, config loader plugins", ".vscode/mcp.json — agent tooling"],
    tunekit: ["config/openai.json — temp=0.1, seed=42, JSON schema", "config/search.json — hybrid 60/40, top-k=5, threshold=0.78", "config/chunking.json — 512 tokens, semantic, 10% overlap", "config/guardrails.json — safety, PII redaction", "evaluation/eval.py — Faithfulness >0.90, Relevance >0.85, Groundedness >0.95"],
    tuningParams: ["temperature (0.1→0.3)", "top-k (5→10)", "chunk_size_tokens (512→256)", "severity_threshold (2→1)"],
    costDev: "$150–300/mo", costProd: "$2K–8K/mo", color: "#10b981", github: "01-enterprise-rag",
  },
  {
    id: "02", slug: "02-ai-landing-zone", name: "AI Landing Zone",
    Icon: Mountain, complexity: "Foundation", status: "Ready",
    tagline: "Foundational Azure infrastructure for AI workloads — networking, identity, governance.",
    description: "Deploy the foundational infrastructure every AI workload needs. VNet with private endpoints keeps traffic off the public internet, Managed Identity eliminates secrets, RBAC locks down access, and Key Vault stores what must be stored. This is Play 0 — run it before anything else.",
    services: ["VNet + Private Endpoints", "RBAC + Managed Identity", "Key Vault", "GPU Quota Management"],
    pattern: "Hub-spoke landing zone, private endpoints, RBAC governance",
    devkit: ["agent.md — infra provisioning assistant", "instructions.md — deployment checklist, security", "copilot-instructions.md — Bicep generation", "mcp/index.js — validate_networking, check_rbac plugins"],
    tunekit: ["config/landing-zone.json — VNet CIDR, subnets, SKUs, GPU quota", "infra/main.bicep — full Bicep template", "infra/parameters.json — region, environment, GPU toggle"],
    tuningParams: ["VNet CIDR range", "Subnet configuration", "Service SKUs", "GPU quota", "Region selection"],
    costDev: "$10–50/mo", costProd: "Included in dependent services", color: "#7c3aed", github: "02-ai-landing-zone",
  },
  {
    id: "03", slug: "03-deterministic-agent", name: "Deterministic Agent",
    Icon: Target, complexity: "Medium", status: "Ready",
    tagline: "Reliable, reproducible AI agent with zero temperature and multi-layer guardrails.",
    description: "When you need AI that gives the same answer every time. Temperature=0, seed pinning, structured JSON output, confidence scoring, anti-sycophancy prompts, and a multi-layer guardrail pipeline. Evaluation suite tests consistency, faithfulness, and safety with zero tolerance for failures.",
    services: ["Container Apps", "Azure OpenAI (gpt-4o, temp=0)", "Content Safety"],
    pattern: "Zero-temp chain, schema validation, anti-sycophancy, confidence scoring",
    devkit: ["agent.md — anti-sycophancy, abstention, citations", "instructions.md — verification chain + structured output", "copilot-instructions.md — guardrail pipeline", "mcp/index.js — validate_response, check_determinism, test_abstention", "plugins/ — guardrail chain, schema validator, citation checker"],
    tunekit: ["config/openai.json — temp=0, seed=42, strict JSON schema", "config/guardrails.json — content safety, injection blocking, confidence ≥0.7", "evaluation/eval.py — Consistency >95%, Faithfulness >0.90, Safety 0 failures"],
    tuningParams: ["temperature (fixed 0)", "seed value", "confidence threshold (0.7)", "schema validation rules"],
    costDev: "$100–250/mo", costProd: "$1.5K–6K/mo", color: "#6366f1", github: "03-deterministic-agent",
  },
  {
    id: "04", slug: "04-call-center-voice-ai", name: "Call Center Voice AI",
    Icon: Phone, complexity: "High", status: "Ready",
    tagline: "Voice-enabled customer service with real-time STT→LLM→TTS streaming.",
    description: "Build a phone-answering AI agent. Azure Communication Services handles the call, Speech Service converts audio to text, GPT-4o processes the intent and generates a response, then TTS speaks it back — all streaming in real time. Includes escalation triggers, PII redaction, and call recording consent flows.",
    services: ["Communication Services", "AI Speech (STT + TTS)", "Azure OpenAI (gpt-4o)", "Container Apps", "Content Safety"],
    pattern: "STT→LLM→TTS streaming pipeline, intent detection, escalation",
    devkit: ["agent.md — voice agent personality", "instructions.md — call flow, escalation rules", "mcp/index.js — voice validation tools", "plugins/ — speech handler, call routing, agent orchestrator"],
    tunekit: ["config/openai.json — model selection, temperature for voice", "config/guardrails.json — PII redaction, consent, profanity filter", "config/agents.json — escalation triggers, hold music", "config/model-comparison.json — GPT-4o vs GPT-4o-mini latency"],
    tuningParams: ["Speech config (language, speed)", "Grounding prompts", "Fallback chains", "Response latency targets", "Audio encoding"],
    costDev: "$200–400/mo", costProd: "$2.5K–10K/mo", color: "#06b6d4", github: "04-call-center-voice-ai",
  },
  {
    id: "05", slug: "05-it-ticket-resolution", name: "IT Ticket Resolution",
    Icon: Ticket, complexity: "Medium", status: "Skeleton",
    tagline: "Auto-classify, route, and resolve IT tickets with event-driven AI.",
    description: "Incoming tickets hit Service Bus, Logic Apps triggers classification via GPT-4o-mini (cheaper, fast enough for triage), the agent routes to the right team or auto-resolves known issues. ServiceNow MCP connector syncs state. Event-driven architecture means it scales to zero when idle.",
    services: ["Logic Apps", "Azure OpenAI (gpt-4o-mini)", "App Service (B1)", "Service Bus"],
    pattern: "Event-driven async automation, ITSM integration",
    devkit: ["agent.md — IT support persona", "instructions.md — routing rules", "mcp/index.js — ticket classification, routing", "plugins/ — ServiceNow connector, classification engine"],
    tunekit: ["config/openai.json — gpt-4o-mini for cost efficiency", "config/agents.json — routing rules, confidence thresholds", "config/guardrails.json — escalation criteria", "evaluation/test-set.jsonl — 50 ticket samples"],
    tuningParams: ["Classification prompts", "Routing rules", "Confidence thresholds", "Escalation criteria"],
    costDev: "$50–150/mo", costProd: "$800–2K/mo", color: "#f97316", github: "05-it-ticket-resolution",
  },
  {
    id: "06", slug: "06-document-intelligence", name: "Document Intelligence",
    Icon: FileText, complexity: "Medium", status: "Skeleton",
    tagline: "Extract, classify, and structure document data with OCR + LLM.",
    description: "Feed PDFs, invoices, receipts, and forms into Azure Document Intelligence for OCR, then GPT-4o extracts structured fields into typed JSON. Cosmos DB stores results. The pipeline handles multi-page documents, handwriting, tables, and stamps. PII masking built in.",
    services: ["Document Intelligence", "Azure OpenAI (gpt-4o)", "Blob Storage", "Cosmos DB"],
    pattern: "OCR+LLM extraction, structured output, form recognition",
    devkit: ["agent.md — doc extraction persona", "instructions.md — extraction rules", "mcp/index.js — doc validation tools", "plugins/ — extraction pipeline, form parser, data mapper"],
    tunekit: ["config/openai.json — extraction prompts, gpt-4o multimodal", "config/extraction-schema.json — field definitions per doc type", "config/guardrails.json — PII masking", "evaluation/test-set.jsonl — doc samples per type"],
    tuningParams: ["Extraction prompts", "Confidence thresholds", "Field schemas", "Document classification rules"],
    costDev: "$80–200/mo", costProd: "$1.2K–3K/mo", color: "#f59e0b", github: "06-document-intelligence",
  },
  {
    id: "07", slug: "07-multi-agent-service", name: "Multi-Agent Service",
    Icon: Bot, complexity: "High", status: "Ready",
    tagline: "Supervisor agent routes to specialist agents with shared state and handoff protocol.",
    description: "A supervisor agent receives requests, classifies intent, and delegates to specialist agents (research, coding, data analysis, etc.). Each agent has its own model config, tools, and memory. Dapr provides state management and pub/sub messaging. Loop prevention and max-iteration guards keep costs predictable.",
    services: ["Container Apps", "Azure OpenAI (gpt-4o, dual)", "Cosmos DB", "Service Bus", "Dapr"],
    pattern: "Agent-to-agent handoff, supervisor pattern, shared state",
    devkit: ["agent.md — supervisor + specialist agents", "instructions.md — handoff protocol", "mcp/index.js — agent routing, state sync", "plugins/ — supervisor logic, agent registry, message broker"],
    tunekit: ["config/openai.json — per-agent model params", "config/guardrails.json — loop prevention, max iterations", "config/agents.json — agent roles, delegation rules, fallback chains", "evaluation/test-set.jsonl — handoff scenarios"],
    tuningParams: ["Supervisor routing logic", "Tool schemas per agent", "Agent memory scope", "Fallback chains", "Max iterations (default 5)"],
    costDev: "$150–350/mo", costProd: "$2K–7K/mo", color: "#8b5cf6", github: "07-multi-agent-service",
  },
  {
    id: "08", slug: "08-copilot-studio-bot", name: "Copilot Studio Bot",
    Icon: MessageCircle, complexity: "Low", status: "Skeleton",
    tagline: "Low-code enterprise bot with Copilot Studio, knowledge grounding, and Dataverse.",
    description: "Build an enterprise chatbot without writing code. Copilot Studio provides the canvas, SharePoint and Dataverse supply the knowledge, AI Search grounds the answers. Topics define conversation flows, and the bot deploys to Teams, web, and mobile. Ideal for HR, IT, and internal knowledge bots.",
    services: ["Copilot Studio", "Dataverse", "SharePoint", "AI Search", "Power Platform"],
    pattern: "Low-code bot, knowledge grounding, topic design",
    devkit: ["agent.md — bot persona", "instructions.md — topic design guide", "plugin.json — Copilot Studio packaging"],
    tunekit: ["config/copilot-studio.json — topic design, intents", "config/knowledge.json — grounding sources", "config/guardrails.json — topic boundaries"],
    tuningParams: ["Topic design", "Knowledge sources", "Confidence thresholds", "Fallback topics"],
    costDev: "$30–80/mo", costProd: "$200–1K/mo", color: "#ec4899", github: "08-copilot-studio-bot",
  },
  {
    id: "09", slug: "09-ai-search-portal", name: "AI Search Portal",
    Icon: Search, complexity: "Medium", status: "Skeleton",
    tagline: "Enterprise search with hybrid ranking and GPT synthesis.",
    description: "A search experience that combines keyword matching with semantic understanding. AI Search handles the retrieval with custom scoring profiles, GPT-4o synthesizes results into readable summaries with citations. Web app frontend with faceted navigation, filters, and autocomplete.",
    services: ["AI Search (semantic)", "Azure OpenAI (gpt-4o)", "App Service (B1)", "Blob Storage"],
    pattern: "Hybrid search + GPT synthesis, scoring profiles",
    devkit: ["agent.md — search assistant", "instructions.md — search semantics guide", "mcp/index.js — search validation tools", "plugins/ — search handler, synthesizer, ranker"],
    tunekit: ["config/search.json — hybrid weights, semantic config, scoring profiles", "config/openai.json — synthesis prompts", "config/ranking.json — custom ranking rules", "evaluation/test-set.jsonl — search query samples"],
    tuningParams: ["Hybrid weights (keyword vs semantic)", "Scoring profiles", "Synthesis prompts", "Result count", "Facet configuration"],
    costDev: "$100–250/mo", costProd: "$1.2K–5K/mo", color: "#0ea5e9", github: "09-ai-search-portal",
  },
  {
    id: "10", slug: "10-content-moderation", name: "Content Moderation",
    Icon: Shield, complexity: "Low", status: "Skeleton",
    tagline: "Filter harmful content with Azure Content Safety and APIM gateway.",
    description: "Every AI response passes through Azure Content Safety for severity scoring across hate, violence, self-harm, and sexual categories. APIM acts as the gateway, enforcing rate limits and routing. Custom blocklists catch domain-specific terms. Azure Functions handle async processing for high-volume scenarios.",
    services: ["Content Safety", "API Management", "Azure Functions"],
    pattern: "Safety gateway, severity scoring, blocklists, custom categories",
    devkit: ["agent.md — safety guardian persona", "instructions.md — moderation rules", "plugins/ — safety pipeline, content blocker"],
    tunekit: ["config/safety.json — severity levels, custom categories, blocklists", "config/guardrails.json — filtering rules, thresholds", "evaluation/ — moderation test sets"],
    tuningParams: ["Severity levels (0–6)", "Custom categories", "Blocklists", "Confidence thresholds"],
    costDev: "$50–100/mo", costProd: "$300–800/mo", color: "#ef4444", github: "10-content-moderation",
  },
  {
    id: "11", slug: "11-ai-landing-zone-advanced", name: "Landing Zone Advanced",
    Icon: Mountain, complexity: "High", status: "Skeleton",
    tagline: "Multi-region, policy-driven enterprise AI infrastructure with firewall and DNS.",
    description: "The enterprise-grade version of Play 02. Multi-region VNets with Azure Firewall, NAT Gateway, custom DNS, Azure Policy enforcement, and network segmentation. Hub-spoke topology with dedicated subnets for AI services, management, and data. Designed for regulated industries needing compliance controls.",
    services: ["Multi-region VNet", "Azure Firewall", "NAT Gateway", "Azure Policy", "Key Vault", "Private Endpoints"],
    pattern: "Enterprise network, segmentation, multi-region, policy enforcement",
    devkit: ["agent.md — enterprise infra architect", "instructions.md — compliance, policies", "mcp/index.js — policy validation, network testing", "plugins/ — network validator, policy checker"],
    tunekit: ["config/network.json — multi-region config, firewall rules, DNS", "config/policy.json — Azure Policy definitions", "infra/main.bicep — Firewall, NAT, segmentation"],
    tuningParams: ["Multi-region layout", "Firewall rules", "Network segmentation", "Policy enforcement", "RBAC scopes"],
    costDev: "$200–500/mo", costProd: "$2K–15K/mo", color: "#7c3aed", github: "11-ai-landing-zone-advanced",
  },
  {
    id: "12", slug: "12-model-serving-aks", name: "Model Serving AKS",
    Icon: Settings, complexity: "High", status: "Skeleton",
    tagline: "Deploy and serve LLMs on AKS with GPU nodes, vLLM, and auto-scaling.",
    description: "Host your own models on Kubernetes. AKS with NVIDIA GPU node pools runs vLLM for high-throughput inference. Auto-scaling based on request queue depth, health checks, and rolling deployments. Supports quantized models (GPTQ, AWQ) for cost efficiency. ACR stores model containers.",
    services: ["AKS (GPU nodes)", "NVIDIA GPU", "Container Registry (ACR)", "vLLM"],
    pattern: "GPU cluster, custom model hosting, LLM inference, auto-scaling",
    devkit: ["agent.md — AKS operations persona", "instructions.md — GPU management guide", "mcp/index.js — GPU validation, cluster health", "plugins/ — vLLM configurator, auto-scaler"],
    tunekit: ["config/aks.json — node pools, GPU config, scaling rules", "config/vllm.json — quantization, batching, max concurrent", "infra/main.bicep — AKS cluster definition"],
    tuningParams: ["GPU node count", "Quantization level (GPTQ/AWQ)", "Batching params", "Scaling rules", "Model weights path"],
    costDev: "$300–600/mo", costProd: "$3K–20K+/mo", color: "#14b8a6", github: "12-model-serving-aks",
  },
  {
    id: "13", slug: "13-fine-tuning-workflow", name: "Fine-Tuning Workflow",
    Icon: Microscope, complexity: "High", status: "Skeleton",
    tagline: "End-to-end fine-tuning with data prep, LoRA training, evaluation, and deployment.",
    description: "Curate training data, configure LoRA parameters, train on Azure ML with GPU compute, evaluate with automated metrics, then deploy the fine-tuned model. MLflow tracks experiments. The pipeline handles data validation, train/val splitting, hyperparameter sweeps, and model versioning.",
    services: ["Azure ML Workspace", "GPU Compute", "Storage", "MLflow", "Azure OpenAI (base models)"],
    pattern: "LoRA fine-tuning, dataset curation, evaluation, MLOps",
    devkit: ["agent.md — ML engineer persona", "instructions.md — training protocols", "mcp/index.js — training validation tools", "plugins/ — data prep, trainer, evaluator"],
    tunekit: ["config/training.json — LoRA rank, learning rate, epochs, batch size", "config/dataset.json — train/val split, preprocessing", "config/evaluation.json — eval metrics, thresholds", "evaluation/eval.py — automated scoring"],
    tuningParams: ["LoRA rank (8–64)", "Learning rate", "Epochs", "Batch size", "Eval metrics thresholds"],
    costDev: "$200–400/mo", costProd: "$1.5K–5K/mo (training)", color: "#f59e0b", github: "13-fine-tuning-workflow",
  },
  {
    id: "14", slug: "14-cost-optimized-ai-gateway", name: "Cost-Optimized AI Gateway",
    Icon: DoorOpen, complexity: "Medium", status: "Skeleton",
    tagline: "APIM-based AI gateway with semantic caching, token budgets, and load balancing.",
    description: "Route AI requests through APIM with semantic caching (Redis stores embeddings of recent queries — similar questions get cached responses). Token budgets per tenant prevent runaway costs. Multi-region load balancing with fallback chains ensures availability. Built-in analytics track cost per team.",
    services: ["API Management", "Redis Cache", "Azure OpenAI (multi-region)"],
    pattern: "Semantic caching, token metering, load balancing, FinOps",
    devkit: ["agent.md — FinOps guardian persona", "instructions.md — caching strategy", "plugins/ — cache handler, budget enforcer, load balancer"],
    tunekit: ["config/gateway.json — caching rules, token budgets, fallback chains", "config/routing.json — load balancing, model selection", "config/pricing.json — cost limits per tenant"],
    tuningParams: ["Token budgets per tenant", "Cache TTL and similarity threshold", "Fallback chains", "Region routing rules", "Model selection per tier"],
    costDev: "$80–200/mo", costProd: "$1K–5K/mo", color: "#10b981", github: "14-cost-optimized-ai-gateway",
  },
  {
    id: "15", slug: "15-multi-modal-docproc", name: "Multi-Modal DocProc",
    Icon: Image, complexity: "Medium", status: "Skeleton",
    tagline: "Process documents with text + images using GPT-4o multi-modal vision.",
    description: "GPT-4o's vision capability processes documents that contain images, charts, tables, and text together. Document Intelligence handles OCR, then GPT-4o interprets visual elements like graphs, stamps, signatures. Outputs structured JSON. Handles multi-page documents with page-level processing.",
    services: ["Azure OpenAI (gpt-4o vision)", "Document Intelligence", "Blob Storage", "Cosmos DB", "Azure Functions"],
    pattern: "Multi-modal extraction, images+text+tables→structured JSON",
    devkit: ["agent.md — multimodal processor persona", "instructions.md — image handling guide", "mcp/index.js — image validation tools", "plugins/ — image processor, table recognizer, extractor"],
    tunekit: ["config/openai.json — gpt-4o, vision prompts", "config/extraction.json — field schemas, image handling rules", "config/guardrails.json — PII in images", "evaluation/ — extraction accuracy per doc type"],
    tuningParams: ["Image prompts", "Extraction schemas", "Confidence thresholds", "Page processing order"],
    costDev: "$120–280/mo", costProd: "$1.5K–4K/mo", color: "#8b5cf6", github: "15-multi-modal-docproc",
  },
  {
    id: "16", slug: "16-copilot-teams-extension", name: "Copilot Teams Extension",
    Icon: Users, complexity: "Medium", status: "Skeleton",
    tagline: "M365 Copilot extension with Graph API, adaptive cards, and declarative agents.",
    description: "Extend Microsoft 365 Copilot with custom skills. Declarative agents define what the copilot can do, Graph API provides organizational data, adaptive cards render rich interactive responses in Teams. App registration in Entra ID handles auth. Deploys to Teams, Outlook, and M365 Chat.",
    services: ["M365 Copilot", "Graph API", "Azure Functions", "Microsoft Entra (App Registration)"],
    pattern: "Teams bot, copilot extension, adaptive cards, Graph integration",
    devkit: ["agent.md — Teams agent persona", "instructions.md — card design guide", "plugins/ — Graph handler, card builder, Teams connector"],
    tunekit: ["config/teams.json — app manifest, adaptive cards", "config/graph.json — permissions, scopes", "config/agents.json — declarative agent config"],
    tuningParams: ["Declarative agent config", "Graph permissions", "Scoping rules", "Adaptive card templates"],
    costDev: "$40–100/mo", costProd: "$200–1K/mo", color: "#6366f1", github: "16-copilot-teams-extension",
  },
  {
    id: "17", slug: "17-ai-observability", name: "AI Observability",
    Icon: BarChart3, complexity: "Medium", status: "Skeleton",
    tagline: "Monitor AI workloads with KQL, quality alerts, and interactive workbooks.",
    description: "Instrument your AI applications with Application Insights, query logs with KQL in Log Analytics, set up quality alerts (latency, error rate, token usage, groundedness scores), and build interactive Azure Workbooks dashboards. Distributed tracing tracks requests across AI Search → OpenAI → your app.",
    services: ["Application Insights", "Log Analytics", "Azure Monitor", "Workbooks"],
    pattern: "KQL dashboards, quality metrics, alerting, APM, distributed tracing",
    devkit: ["agent.md — observability engineer persona", "instructions.md — KQL guide", "plugins/ — KQL generator, alert builder, workbook designer"],
    tunekit: ["config/monitoring.json — KQL queries, alert thresholds, dashboards", "config/metrics.json — quality KPIs", "infra/ — workbook templates"],
    tuningParams: ["KQL queries", "Alert thresholds", "Quality metrics definitions", "Dashboard layouts"],
    costDev: "$30–80/mo", costProd: "$200–1K/mo", color: "#0ea5e9", github: "17-ai-observability",
  },
  {
    id: "18", slug: "18-prompt-management", name: "Prompt Management",
    Icon: FileEdit, complexity: "Medium", status: "Skeleton",
    tagline: "Version control, A/B test, and rollback prompts across environments.",
    description: "Manage prompts like code. Git-backed versioning, A/B testing with traffic splitting, automated quality scoring per version, rollback to any previous version. Cosmos DB stores prompt versions and experiment results. GitHub Actions CI/CD deploys prompt updates across dev/staging/prod.",
    services: ["Prompt Flow", "Git/GitHub", "GitHub Actions", "Azure AI Foundry", "Cosmos DB"],
    pattern: "Prompt versioning, A/B testing, CI/CD, rollback, experimentation",
    devkit: ["agent.md — prompt engineer persona", "instructions.md — versioning protocol", ".github/workflows — CI/CD pipelines", "plugins/ — version manager, A/B tester, rollback handler"],
    tunekit: ["config/prompts.json — prompt versions, active versions", "config/ab-test.json — A/B weights, experiment tracking", "infra/ — Prompt Flow templates"],
    tuningParams: ["Prompt versions", "A/B traffic weights", "Rollback rules", "Version scheduling"],
    costDev: "$50–150/mo", costProd: "$300–1K/mo", color: "#f97316", github: "18-prompt-management",
  },
  {
    id: "19", slug: "19-edge-ai-phi4", name: "Edge AI Phi-4",
    Icon: Smartphone, complexity: "High", status: "Skeleton",
    tagline: "Deploy Phi-4 SLM on edge devices with ONNX quantization and offline inference.",
    description: "Run a small language model on edge devices without cloud connectivity. Phi-4 quantized to INT4 via ONNX Runtime runs on devices with 4GB+ RAM. IoT Hub manages device fleet, syncs model updates, and collects telemetry. Supports offline inference with periodic cloud sync for model updates.",
    services: ["IoT Hub", "Container Instances", "ONNX Runtime", "Azure Storage"],
    pattern: "Edge AI, SLM, ONNX quantization, offline inference, device sync",
    devkit: ["agent.md — edge AI engineer persona", "instructions.md — device management guide", "plugins/ — ONNX optimizer, device syncer, inference tester"],
    tunekit: ["config/edge.json — quantization level, model config, memory constraints", "config/sync.json — update schedule, rollback rules"],
    tuningParams: ["Quantization level (INT4/INT8)", "Model config", "Sync schedule", "Device memory budget"],
    costDev: "$20–50/mo", costProd: "$100–500/mo", color: "#14b8a6", github: "19-edge-ai-phi4",
  },
  {
    id: "20", slug: "20-anomaly-detection", name: "Anomaly Detection",
    Icon: AlertTriangle, complexity: "High", status: "Skeleton",
    tagline: "Real-time anomaly detection with streaming analysis and AI enrichment.",
    description: "Events flow through Event Hub, Stream Analytics detects statistical anomalies in real time, GPT-4o enriches alerts with natural language explanations and suggested actions. Cosmos DB stores event history for trend analysis. Azure Functions trigger downstream workflows (PagerDuty, Teams, email).",
    services: ["Event Hub", "Stream Analytics", "Azure OpenAI (gpt-4o)", "Azure Functions", "Cosmos DB"],
    pattern: "Streaming anomaly detection, event-driven, AI enrichment, alerting",
    devkit: ["agent.md — anomaly detective persona", "instructions.md — detection logic guide", "plugins/ — event processor, anomaly scorer, alerter"],
    tunekit: ["config/detection.json — detection models, sensitivity, thresholds", "config/alerts.json — alert rules, severity mapping", "config/enrichment.json — AI analysis prompts"],
    tuningParams: ["Detection thresholds", "Alert prompts", "Sensitivity levels", "Detection windows"],
    costDev: "$100–250/mo", costProd: "$1.2K–4K/mo", color: "#ef4444", github: "20-anomaly-detection",
  },
];

export function getPlayBySlug(slug: string): PlayData | undefined {
  return plays.find(p => p.slug === slug);
}

export function getAllSlugs(): string[] {
  return plays.map(p => p.slug);
}
