targetScope = 'resourceGroup'

// AI Landing Zone — Azure Infrastructure
// SKELETON: Full Bicep implementation will be generated by the AI agent.
//
// Resources: VNet, Private Endpoints, Managed Identity, RBAC, Azure OpenAI,
// AI Search, Storage, Key Vault, Container Apps Env, Log Analytics, App Insights

@description('Location for all resources')
param location string = resourceGroup().location

@description('Environment name')
param environmentName string = 'ai-prod'

@description('OpenAI model')
param openaiModelName string = 'gpt-4o'

@description('Enable GPU quota reservation')
param enableGpuQuota bool = false
