import { ArrowRight, BarChart3, Bot, Boxes, ExternalLink, FlaskConical, Gauge, Layers3, Shield, Sparkles, Sprout, Workflow } from "lucide-react";
import { vscode } from "../vscode";

const PRODUCTS: Record<string, { eyebrow: string; title: string; description: string; color: string; Icon: typeof Sprout; capabilities: Array<[string, string]>; primaryRoute?: string; external: string }> = {
  orchard: { eyebrow: "Govern source intelligence", title: "FAI Orchard", description: "Discover, inspect, harvest, package, and govern reusable AI accelerators with explicit source identity and evidence.", color: "#10b981", Icon: Sprout, external: "https://www.frootai.dev/orchard", capabilities: [["Discover", "Inspect source identity, ownership, license, capabilities, and freshness."], ["Harvest", "Convert repository evidence into bounded accelerator metadata."], ["Package", "Produce governed artifacts while preserving provenance."], ["Promote", "Move approved evidence toward a canonical Solution Play."]], primaryRoute: "/solution-accelerator" },
  studio: { eyebrow: "Compose governed systems", title: "FrootAI Studio", description: "Design inspectable AI solutions from architecture nodes, Play contracts, primitives, evidence, quality gates, and cost controls.", color: "#a78bfa", Icon: Workflow, external: "https://www.frootai.dev/app", capabilities: [["Design", "Compose architecture and implementation assets visually."], ["Inspect", "Review configuration, evidence, and operation boundaries."], ["Evaluate", "Track quality, risk, readiness, and cost before promotion."], ["Export", "Move a bounded design into a repository-native delivery system."]], primaryRoute: "/solution-plays" },
  lab: { eyebrow: "Verify exact artifacts", title: "FAI Lab", description: "Measure quality, groundedness, safety, latency, and repeatability against explicit evidence and thresholds.", color: "#ec4899", Icon: FlaskConical, external: "https://www.frootai.dev/lab", capabilities: [["Datasets", "Define representative evaluation inputs and expected behavior."], ["Metrics", "Score groundedness, relevance, coherence, fluency, and safety."], ["Evidence", "Keep outputs and verdicts tied to exact artifacts."], ["Improve", "Tune only against measured gaps and rerun the same gates."]], primaryRoute: "/evaluation" },
  lean: { eyebrow: "Optimize measured fidelity", title: "FAI Lean Mode", description: "Reduce prompt and context cost while preserving required meaning, controls, and verified output quality.", color: "#f59e0b", Icon: Gauge, external: "https://www.frootai.dev/lean", capabilities: [["Measure", "Establish a token and behavior baseline before optimization."], ["Compile", "Remove redundancy without removing semantic requirements."], ["Compare", "Evaluate Full and Lean forms against the same cases."], ["Promote", "Adopt only when fidelity and control thresholds remain satisfied."]], primaryRoute: "/docs/R3" },
};

export default function ProductOverview({ product, onNavigate }: { product: string; onNavigate: (route: string) => void }) {
  const info = PRODUCTS[product] ?? PRODUCTS.studio;
  return <main className="container fai-product-overview"><section className="fai-content-hero" style={{ "--product-color": info.color } as React.CSSProperties}><div><span className="fai-eyebrow"><info.Icon size={13} /> {info.eyebrow}</span><h1>{info.title}</h1><p>{info.description}</p><div className="fai-detail-actions">{info.primaryRoute && <button className="btn" onClick={() => onNavigate(info.primaryRoute!)}>Open native workflow <ArrowRight size={12} /></button>}<button className="btn btn-secondary" onClick={() => vscode.postMessage({ command: "openUrl", url: info.external })}>Inspect web surface <ExternalLink size={11} /></button></div></div><aside><strong>FAI</strong><span>native product</span><strong>1</strong><span>workbench</span></aside></section><section className="fai-product-capabilities">{info.capabilities.map(([title, detail], index) => <article key={title}><span>{String(index + 1).padStart(2, "0")}</span>{index === 0 ? <Boxes size={18} /> : index === 1 ? <Layers3 size={18} /> : index === 2 ? <Shield size={18} /> : <Sparkles size={18} />}<h2>{title}</h2><p>{detail}</p></article>)}</section><section className="fai-product-handoff"><Bot size={20} /><div><span className="fai-eyebrow">Connected FAI system</span><h2>Continue without leaving this tab.</h2><p>Navigate between source intelligence, Solution Plays, MCP tools, Docs, and Glossary while preserving your workbench context.</p></div><button className="btn btn-secondary" onClick={() => onNavigate("/solution-plays")}>Browse Plays <ArrowRight size={12} /></button></section></main>;
}
