import { AlertTriangle, ArrowRight, CheckCircle2, Code2, FileSearch, ShieldCheck } from "lucide-react";
import type { RepositoryReportView } from "../types";
import { vscode } from "../vscode";

export default function RepositoryIntelligence({ report }: { report?: RepositoryReportView }) {
  if (!report) return <main className="container"><div className="empty-state">No repository report is available.</div></main>;
  return <main className="container fai-repository-report">
    <section className="hero"><p className="fai-eyebrow">Discover → Define</p><h1>Repository Intelligence</h1><p>{report.name} · {report.fileCount.toLocaleString()} paths mapped · {report.inspectedMetadataCount.toLocaleString()} allowlisted metadata files inspected{report.truncated ? " · bounded at 5,000" : ""}</p></section>
    <div className="fai-repository-trust"><ShieldCheck size={15} /><span><strong>Local and read-only.</strong> Only bounded paths and allowlisted metadata were inspected; no source was uploaded.</span></div>
    <section className="fai-repository-purpose"><article><strong>01 · Detect</strong><p>Identify architecture, AI, infrastructure, safety, and evaluation signals from allowlisted metadata.</p></article><article><strong>02 · Explain</strong><p>Show the exact repository paths that produced every signal—no opaque score.</p></article><article><strong>03 · Recommend</strong><p>Rank complete Solution Plays and open each delivery contract directly in this workbench.</p></article></section>
    <section className="section"><div className="section-title">Technology inventory</div>{report.technologies.length ? <div className="fai-technology-grid">{report.technologies.map((technology) => <article key={technology.name}><Code2 size={15} /><div><strong>{technology.name}</strong><span>{technology.files.toLocaleString()} matching files</span><p>{technology.evidence.join(" · ")}</p></div></article>)}</div> : <div className="fai-repository-empty"><AlertTriangle size={16} /><span><strong>No implementation stack detected yet.</strong>Add source files or a package/build manifest, then analyze again.</span></div>}</section>
    <section className="section"><div className="section-title">Detected system</div><div className="fai-signal-grid">{report.signals.map((signal) => <article key={signal.id}><CheckCircle2 size={14} /><div><strong>{signal.label}</strong><p>{signal.evidence.join(" · ")}</p></div></article>)}</div></section>
    <section className="section"><div className="section-title">Production readiness map</div><div className="fai-readiness-grid">{report.readiness.map((item) => <article key={item.id} className={item.status}><span>{item.status === "detected" ? <CheckCircle2 size={15} /> : <AlertTriangle size={15} />}</span><div><strong>{item.label}</strong><small>{item.status === "detected" ? "Evidence detected" : "Gap to address"}</small><p>{item.detail}</p>{item.evidence.length > 0 && <code>{item.evidence.join(" · ")}</code>}</div></article>)}</div></section>
    <section className="section"><div className="section-title">{report.recommendationMode === "evidence-ranked" ? "Evidence-ranked Solution Plays" : "Generic starter Plays"}</div>{report.recommendationMode === "generic-starters" && <p className="fai-repository-disclosure">No architecture-specific evidence was detected, so these are transparent starting points—not repository-derived rankings. Add a README, manifest, source, or infrastructure files and analyze again for tailored matching.</p>}<div className="fai-recommendation-list">{report.recommendations.map((recommendation, index) => <button key={recommendation.play.id} onClick={() => vscode.postMessage({ command: "openPlay", playId: recommendation.play.id })}><span>{String(index + 1).padStart(2, "0")}</span><div><strong>Play {recommendation.play.id} · {recommendation.play.name}</strong><p>{recommendation.play.tagline ?? recommendation.play.desc}</p><small>{recommendation.reasons.join(" · ")}</small></div><ArrowRight size={14} /></button>)}</div></section>
    <footer><button className="btn btn-secondary" onClick={() => vscode.postMessage({ command: "analyzeRepository" })}><FileSearch size={13} /> Analyze again</button><button className="btn" onClick={() => vscode.postMessage({ command: "openConfigurator" })}>Refine with Configurator <ArrowRight size={13} /></button></footer>
  </main>;
}
