// @generated — This file is auto-generated by FAI Factory
// Do not edit manually. Run: npm run factory
// Generated: 2026-04-18T10:21:58.327Z

export const STATS = {
  "agents": 238,
  "skills": 333,
  "instructions": 176,
  "hooks": 10,
  "plugins": 77,
  "workflows": 12,
  "cookbook": 16,
  "plays": 104,
  "modules": 24,
  "mcpTools": 45,
  "totalPrimitives": 862
} as const;

export const EMBEDDED_STATS = {
  "agents": 306,
  "skills": 304,
  "instructions": 304,
  "hooks": 101
} as const;
