// @ts-check
/**
 * FAI MCP CLI — shell completion script generators (M4.18 ship).
 *
 * Pure module: every export is a `() => string` (or a thin wrapper that
 * builds a string from constants). Dispatcher's `--completion <shell>`
 * meta-flag pipes the output to stdout so operators can eval it into
 * their shell rc files.
 *
 * Bash lands at M4.18. PowerShell + Zsh PIN_ONE_AHEAD to M4.19 / M4.20.
 */
"use strict";

const { McpCliError } = require("./cli-error");

/**
 * The 8 subcommand names registered by the M4.1 dispatcher. Mirrored
 * here as a flat constant so the completion script can be generated
 * without booting the dispatcher (and so a drift between the two
 * surfaces is immediately visible via the M4.18 gate).
 */
const SUBCOMMANDS = Object.freeze([
  "list", "discover", "attach", "detach", "trust", "test", "invoke", "publish",
]);

/** `frootai mcp trust <action>` sub-actions (M4.7-M4.9). */
const TRUST_ACTIONS = Object.freeze(["list", "set", "unset"]);

/** `frootai mcp trust set <publisher> <tier>` tier enum (M4.8). */
const TRUST_TIERS = Object.freeze([
  "first-party-ms", "verified-publisher", "community", "untrusted",
]);

/** `frootai mcp discover --tier T1|T2|T3` enum (M4.4). */
const DISCOVER_TIERS = Object.freeze(["T1", "T2", "T3"]);

/**
 * Flags accepted by each subcommand. Only the long form is enumerated;
 * the bash completion suggests `--name` and lets the operator append
 * a value freely. PIN_ONE_AHEAD: the M4.21 deterministic-exit row may
 * tighten this further once `--verbose`/`--no-network` land at M4.25/M4.26.
 */
const SUBCOMMAND_FLAGS = Object.freeze({
  list:     ["--json", "--no-color"],
  discover: ["--json", "--no-color", "--tier", "--limit", "--refresh"],
  attach:   ["--json", "--no-color", "--trust-override"],
  detach:   ["--json", "--no-color"],
  trust:    ["--json", "--no-color"],
  test:     ["--json", "--no-color", "--all"],
  invoke:   ["--json", "--no-color", "--args", "--persist"],
  publish:  ["--json", "--no-color", "--submit"],
});

const SUPPORTED_SHELLS = Object.freeze(["bash", "powershell", "zsh"]);

/**
 * Render the bash completion script. Pure; depends only on the constants
 * above so the generator output is deterministic across runs.
 *
 * Operators install via:
 *   `frootai mcp --completion bash >> ~/.bashrc`
 * or (preferred — survives upgrades):
 *   `frootai mcp --completion bash | sudo tee /etc/bash_completion.d/frootai-mcp`
 *
 * @returns {string}
 */
function generateBashCompletion() {
  // Per-subcommand flag arrays serialised as bash strings.
  const flagBlock = Object.entries(SUBCOMMAND_FLAGS)
    .map(([sub, flags]) => `      ${sub})\n        opts="${flags.join(" ")}"\n        ;;`)
    .join("\n");

  return `# frootai mcp bash completion (M4.18)
# Generated by \`frootai mcp --completion bash\`.
# Install:
#   eval "$(frootai mcp --completion bash)"            # current shell only
#   frootai mcp --completion bash >> ~/.bashrc         # persistent (user)
#   frootai mcp --completion bash | sudo tee \\
#     /etc/bash_completion.d/frootai-mcp               # persistent (system)

_frootai_mcp() {
  local cur prev words cword
  _init_completion || return

  # Position 1 = subcommand. Operator typed: \`frootai mcp <TAB>\`.
  if [[ $cword -eq 2 ]]; then
    COMPREPLY=( $(compgen -W "${SUBCOMMANDS.join(" ")} help" -- "$cur") )
    return
  fi

  local sub="\${words[2]}"

  # Position 2 of \`trust\` subcommand = list / set / unset.
  if [[ "$sub" == "trust" && $cword -eq 3 ]]; then
    COMPREPLY=( $(compgen -W "${TRUST_ACTIONS.join(" ")}" -- "$cur") )
    return
  fi

  # Position 3 of \`trust set <pub> <tier>\` = tier enum.
  if [[ "$sub" == "trust" && "\${words[3]}" == "set" && $cword -eq 5 ]]; then
    COMPREPLY=( $(compgen -W "${TRUST_TIERS.join(" ")}" -- "$cur") )
    return
  fi

  # Value-completing flags.
  case "$prev" in
    --tier)
      COMPREPLY=( $(compgen -W "${DISCOVER_TIERS.join(" ")}" -- "$cur") )
      return
      ;;
  esac

  # Flag completion for the chosen subcommand.
  local opts="--json --no-color --help"
  case "$sub" in
${flagBlock}
  esac
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
    return
  fi
}

# Wire the function to both \`frootai mcp\` and \`fai mcp\` (alias bin in cli/package.json).
complete -F _frootai_mcp frootai
complete -F _frootai_mcp fai
`;
}

/**
 * Render the PowerShell completion script. Pure; depends only on the
 * constants above so the generator output is deterministic across runs.
 *
 * Operators install via:
 *   `frootai mcp --completion powershell | Out-String | Invoke-Expression`   # current session
 *   `frootai mcp --completion powershell >> $PROFILE`                        # persistent
 *
 * Uses `Register-ArgumentCompleter -Native` so PowerShell drives the
 * completion via the native-command bridge (works on PowerShell 7+,
 * Windows PowerShell 5.1 with the `PSReadLine` module, and pwsh on
 * macOS / Linux).
 *
 * @returns {string}
 */
function generatePowerShellCompletion() {
  const subList = SUBCOMMANDS.map((s) => `'${s}'`).join(", ");
  const subListWithHelp = SUBCOMMANDS.concat(["help"]).map((s) => `'${s}'`).join(", ");
  const trustActions = TRUST_ACTIONS.map((s) => `'${s}'`).join(", ");
  const trustTiers = TRUST_TIERS.map((s) => `'${s}'`).join(", ");
  const discoverTiers = DISCOVER_TIERS.map((s) => `'${s}'`).join(", ");
  const flagSwitch = Object.entries(SUBCOMMAND_FLAGS)
    .map(([sub, flags]) => `        '${sub}' { @(${flags.map((f) => `'${f}'`).join(", ")}) }`)
    .join("\n");

  return `# frootai mcp PowerShell completion (M4.19)
# Generated by \`frootai mcp --completion powershell\`.
# Install:
#   frootai mcp --completion powershell | Out-String | Invoke-Expression   # current session
#   frootai mcp --completion powershell >> $PROFILE                        # persistent
# Verify $PROFILE path:  $PROFILE | Select-Object -ExpandProperty FullName

Register-ArgumentCompleter -Native -CommandName 'frootai','fai' -ScriptBlock {
    param($wordToComplete, $commandAst, $cursorPosition)

    $tokens = @($commandAst.CommandElements | ForEach-Object { $_.ToString() })
    # tokens[0] == 'frootai' | 'fai'. We only complete the \`mcp\` subtree.
    if ($tokens.Count -lt 2 -or $tokens[1] -ne 'mcp') { return }

    $allSubs = @(${subListWithHelp})
    $trustActions = @(${trustActions})
    $trustTiers = @(${trustTiers})
    $discoverTiers = @(${discoverTiers})

    # tokens[2] = subcommand. If the cursor is parked on it (or it's missing),
    # surface the 8 subcommand names.
    if ($tokens.Count -lt 3 -or ($tokens.Count -eq 3 -and -not $wordToComplete.StartsWith('-'))) {
        return $allSubs |
            Where-Object { $_ -like "$wordToComplete*" } |
            ForEach-Object { [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_) }
    }

    $sub = $tokens[2]

    # \`trust <action>\`
    if ($sub -eq 'trust' -and $tokens.Count -eq 4 -and -not $wordToComplete.StartsWith('-')) {
        return $trustActions |
            Where-Object { $_ -like "$wordToComplete*" } |
            ForEach-Object { [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_) }
    }

    # \`trust set <publisher> <tier>\` \u2014 tier enum at position 4 (zero-indexed: tokens[5]).
    if ($sub -eq 'trust' -and $tokens.Count -ge 5 -and $tokens[3] -eq 'set' -and $tokens.Count -eq 6 -and -not $wordToComplete.StartsWith('-')) {
        return $trustTiers |
            Where-Object { $_ -like "$wordToComplete*" } |
            ForEach-Object { [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_) }
    }

    # Value-completing flags. If the previous token is \`--tier\`, suggest T1/T2/T3.
    $prev = if ($tokens.Count -ge 2) { $tokens[$tokens.Count - 2] } else { '' }
    if ($prev -eq '--tier' -and -not $wordToComplete.StartsWith('-')) {
        return $discoverTiers |
            Where-Object { $_ -like "$wordToComplete*" } |
            ForEach-Object { [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_) }
    }

    # Per-subcommand flag completion.
    $opts = switch ($sub) {
${flagSwitch}
        default { @('--json', '--no-color', '--help') }
    }
    if ($wordToComplete.StartsWith('-')) {
        return $opts |
            Where-Object { $_ -like "$wordToComplete*" } |
            ForEach-Object { [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterName', $_) }
    }
}
`;
}

/**
 * Render the zsh completion script. Pure; depends only on the constants
 * above so the generator output is deterministic across runs.
 *
 * Operators install via:
 *   eval "$(frootai mcp --completion zsh)"                         # current shell only
 *   frootai mcp --completion zsh > ~/.config/zsh/completions/_frootai
 *   # then ensure `fpath=(~/.config/zsh/completions $fpath)` is in ~/.zshrc
 *   # and `autoload -Uz compinit && compinit` (most distros do this already).
 *
 * Uses the `#compdef` directive so zsh's completion system picks it up
 * automatically when loaded via `fpath` + `compinit`.
 *
 * @returns {string}
 */
function generateZshCompletion() {
  const subList = SUBCOMMANDS.map((s) => `'${s}:${s}'`).join(" ");
  const subListWithHelp = [...SUBCOMMANDS, "help"].map((s) => `'${s}:${s}'`).join(" ");
  const trustActions = TRUST_ACTIONS.map((s) => `'${s}:${s}'`).join(" ");
  const trustTiers = TRUST_TIERS.map((s) => `'${s}'`).join(" ");
  const discoverTiers = DISCOVER_TIERS.map((s) => `'${s}'`).join(" ");
  const flagSwitch = Object.entries(SUBCOMMAND_FLAGS)
    .map(([sub, flags]) => `      ${sub})\n        opts+=(${flags.map((f) => `'${f}'`).join(" ")})\n        ;;`)
    .join("\n");

  return `#compdef frootai fai
# frootai mcp zsh completion (M4.20)
# Generated by \`frootai mcp --completion zsh\`.
# Install:
#   eval "$(frootai mcp --completion zsh)"                                  # current shell only
#   frootai mcp --completion zsh > ~/.config/zsh/completions/_frootai       # persistent
#   # then ensure ~/.zshrc has:
#   #   fpath=(~/.config/zsh/completions $fpath)
#   #   autoload -Uz compinit && compinit

_frootai_mcp_completion() {
  # Only handle the \`mcp\` subcommand group; let zsh fall through to other
  # completers (e.g. the orchard group) when the operator typed a different
  # top-level subcommand.
  if [[ "\${words[2]}" != "mcp" ]]; then
    return 0
  fi

  local -a subcommands trust_actions trust_tiers discover_tiers opts
  subcommands=(${subListWithHelp})
  trust_actions=(${trustActions})
  trust_tiers=(${trustTiers})
  discover_tiers=(${discoverTiers})

  # Layout: words[1]=frootai|fai, words[2]=mcp, words[3]=subcommand, ...
  # CURRENT is the cursor word index (1-based in zsh).
  if (( CURRENT == 3 )); then
    _describe 'subcommand' subcommands
    return
  fi

  local sub="\${words[3]}"

  # \`trust <action>\` at CURRENT=4
  if [[ "$sub" == "trust" ]]; then
    if (( CURRENT == 4 )); then
      _describe 'trust action' trust_actions
      return
    fi
    # \`trust set <publisher> <tier>\` \u2014 tier enum at CURRENT=6
    if [[ "\${words[4]}" == "set" && CURRENT -eq 6 ]]; then
      _values 'trust tier' ${trustTiers}
      return
    fi
  fi

  # Value-completing flags. zsh's words[CURRENT-1] is the previous token.
  local prev="\${words[CURRENT-1]}"
  if [[ "$prev" == "--tier" ]]; then
    _values 'discover tier' ${discoverTiers}
    return
  fi

  # Per-subcommand flag completion.
  opts=('--json' '--no-color' '--help')
  case "$sub" in
${flagSwitch}
  esac
  _values 'option' \${opts[@]}
}

compdef _frootai_mcp_completion frootai fai
`;
}

/**
 * Dispatch `--completion <shell>` to the correct generator. Used by the
 * top-level dispatcher to fast-path completion requests before normal
 * subcommand routing.
 *
 * @param {string} shell
 * @returns {string}
 */
function generateCompletion(shell) {
  if (typeof shell !== "string" || shell.length === 0) {
    throw new McpCliError(
      "user_error",
      "--completion requires a shell argument",
      { hint: `Allowed: ${SUPPORTED_SHELLS.join(" | ")}` },
    );
  }
  const s = shell.toLowerCase();
  if (s === "bash") return generateBashCompletion();
  if (s === "powershell" || s === "pwsh") return generatePowerShellCompletion();
  if (s === "zsh") return generateZshCompletion();
  throw new McpCliError(
    "user_error",
    `unsupported completion shell "${shell}"`,
    { hint: `Allowed: ${SUPPORTED_SHELLS.join(" | ")}` },
  );
}

module.exports = {
  SUBCOMMANDS,
  TRUST_ACTIONS,
  TRUST_TIERS,
  DISCOVER_TIERS,
  SUBCOMMAND_FLAGS,
  SUPPORTED_SHELLS,
  generateBashCompletion,
  generatePowerShellCompletion,
  generateZshCompletion,
  generateCompletion,
};
